(function() {
var _UDS_CONST_LOCALE = 'es';
var _UDS_CONST_SHORT_DATE_PATTERN = 'DMY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('Imagen'); 
var _UDS_MSG_SEARCHER_WEB = ('web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blog'); 
var _UDS_MSG_SEARCHER_VIDEO = ('V\u00eddeo'); 
var _UDS_MSG_SEARCHER_LOCAL = ('Local'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('guardar'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('conservar'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('incluir'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('copiar'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('cerrar'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Enlaces patrocinados'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('ver m\u00e1s...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('recortado de Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('Ubicaci\u00f3n relacionada con la b\u00fasqueda'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Inhabilitar la b\u00fasqueda de direcciones'); 
var _UDS_MSG_SEARCHER_NEWS = ('Noticias'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('hace ' + AGE_MINUTES_AGO + ' minutos');} 
var _UDS_MSG_ONE_HOUR_AGO = ('hace 1 hora'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('hace ' + AGE_HOURS_AGO + ' horas');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('y ' + NUMBER + ' art\u00edculos relacionados');} 
var _UDS_MSG_NEWS_RELATED = ('Art\u00edculos relacionados'); 
var _UDS_MSG_BRANDING_STRING = ('con la tecnolog\u00eda de Google'); 
var _UDS_MSG_SORT_BY_DATE = ('Ordenar por fecha'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Ene'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Feb'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Mar'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Abr'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('May'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Jun'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Jul'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Ago'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Sep'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Oct'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Nov'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Dic'); 
var _UDS_MSG_DIRECTIONS = ('direcciones'); 
var _UDS_MSG_CLEAR_RESULTS = ('borrar resultados'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('mostrar un resultado'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('mostrar m\u00e1s resultados'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('mostrar todos los resultados'); 
var _UDS_MSG_SETTINGS = ('ajustes'); 
var _UDS_MSG_SEARCH = ('buscar'); 
var _UDS_MSG_SEARCH_UC = ('Buscar'); 
var _UDS_MSG_POWERED_BY = ('con la tecnolog\u00eda de'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Directorios empresariales proporcionados por ' + LOCAL_RESULTS_PROVIDER);} 
var _UDS_MSG_SEARCHER_BOOK = ('B\u00fasqueda de libros'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('P\u00e1gina ' + FOUND_ON_PAGE);} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' p\u00e1ginas');} 
var _UDS_MSG_SEARCHER_BY = ('de'); 
var _UDS_MSG_SEARCHER_CODE = ('C\u00f3digo'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Licencia desconocida'); 
var _UDS_MSG_SEARCHER_GSA = ('Google Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('M\u00e1s resultados'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Anterior'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Siguiente'); 
var _UDS_MSG_GET_DIRECTIONS = ('Obtener indicaciones'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('Hasta aqu\u00ed'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('Desde aqu\u00ed'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('Borrar resultados'); 
var _UDS_MSG_SEARCH_THE_MAP = ('buscar en el mapa'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('desplazarse por los resultados'); 
var _UDS_MSG_EDIT_TAGS = ('editar etiquetas'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('etiquetar esta b\u00fasqueda'); 
var _UDS_MSG_SEARCH_STRING = ('cadena de b\u00fasqueda'); 
var _UDS_MSG_OPTIONAL_LABEL = ('etiqueta opcional'); 
var _UDS_MSG_DELETE = ('suprimir'); 
var _UDS_MSG_DELETED = ('suprimido'); 
var _UDS_MSG_CANCEL = ('cancelar'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('subir tu propio v\u00eddeo'); 
var _UDS_MSG_IM_DONE_WATCHING = ('he acabado de verlo'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('cerrar reproductor de v\u00eddeo'); 
var _UDS_MSG_NO_RESULTS = ('No hay resultados.'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('El motor de b\u00fasqueda de cupones se est\u00e1 cargando. Vuelve a intentarlo transcurridos unos segundos.'); 
var _UDS_MSG_COUPONS = ('Cupones'); 
var _UDS_MSG_BACK = ('atr\u00e1s'); 
var _UDS_MSG_SUBSCRIBE = ('Suscribirse'); 
var _UDS_MSG_SEARCHER_PATENT = ('Patente'); 
var _UDS_MSG_USPAT = ('Patente estadounidense'); 
var _UDS_MSG_USPAT_APP = ('Solicitud de patente estadounidense'); 
var _UDS_MSG_PATENT_FILED = ('Presentado'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Anuncios Google'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('Definir ubicaci\u00f3n predeterminada'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('Noticias destacadas'); 
var _UDS_MSG_NEWSCAT_WORLD = ('Internacional'); 
var _UDS_MSG_NEWSCAT_NATION = ('Nacional'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Econom\u00eda'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Ciencia/Tecn.'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Espect\u00e1culos'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('Salud'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Deportes'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Pol\u00edtica');
var b=void 0,f=null,h=encodeURIComponent,j=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,k=window,m=document,n=Math,ba=navigator,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,fa=decodeURIComponent;function ga(a,c){return a.input=c}function ha(a,c){return a.width=c}function o(a,c){return a.innerHTML=c}function q(a,c){return a.value=c}function ia(a,c){return a.type=c}function ja(a,c){return a.title=c}function r(a,c){return a.className=c}function ka(a,c){return a.checked=c}
function la(a,c){return a.next=c}function ma(a,c){return a.target=c}function na(a,c){return a.onclick=c}function oa(a,c){return a.display=c}function pa(a,c){return a.execute=c}function qa(a,c){return a.height=c}function ra(a,c){return a.root=c}
var s="appendChild",sa="push",ta="show",ua="clearTimeout",t="input",v="width",va="submit",wa="round",w="replace",xa="nodeType",ya="floor",za="content",x="getElementById",Aa="offsetWidth",Ba="sessionStorage",y="value",Ca="indexOf",Da="match",Ea="focus",A="createElement",Fa="keyCode",B="firstChild",C="setAttribute",Ga="cloneNode",Ha="type",Ia="ServiceBase",Ja="nextSibling",D="getTime",Ka="getElementsByTagName",La="toString",E="length",Ma="title",F="prototype",H="cursor",Na="className",Oa="Version",
Pa="checked",Qa="setTimeout",Ra="next",Sa="split",Ta="offsetParent",Ua="location",Va="getComputedStyle",I="style",Wa="close",Xa="body",Ya="removeChild",J="search",K="call",L="loader",Za="currentStyle",$a="href",ab="themes",bb="apply",cb="parentNode",db="CurrentLocale",M="execute",eb="height",N="root",fb="join",gb="toLowerCase",hb="event",O;google[J].NoOldNames||(j("UDS_ServiceBase",google[L][Ia]),j("UDS_ApiKey",google[L].ApiKey),j("UDS_KeyVerified",google[L].KeyVerified),j("UDS_LoadFailure",google[L].LoadFailure),j("UDS_CurrentLocale",ea),j("UDS_ShortDatePattern",aa),j("UDS_Version",google[J][Oa]),j("UDS_JSHash",google[J].JSHash));if(!P)var P=j;if(!Q)var Q=google_exportProperty;var R={blank:"&nbsp;"};R.image=_UDS_MSG_SEARCHER_IMAGE;R.web=_UDS_MSG_SEARCHER_WEB;R.blog=_UDS_MSG_SEARCHER_BLOG;R.video=_UDS_MSG_SEARCHER_VIDEO;R.local=_UDS_MSG_SEARCHER_LOCAL;R.news=_UDS_MSG_SEARCHER_NEWS;R.book=_UDS_MSG_SEARCHER_BOOK;R.patent="Patent";R["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;R.cse="Custom Search Control";R.save=_UDS_MSG_SEARCHCONTROL_SAVE;R.keep=_UDS_MSG_SEARCHCONTROL_KEEP;R.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;R.copy=_UDS_MSG_SEARCHCONTROL_COPY;R.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
R["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;R["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;R.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;R["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;R["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;R["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;R.pbg=_UDS_MSG_BRANDING_STRING;R["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;R["n-hours-ago"]=_UDS_MSG_HOURS_AGO;R["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;R["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
R["related-articles"]=_UDS_MSG_NEWS_RELATED;R["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var ib=[];ib[0]=_UDS_MSG_MONTH_ABBR_JAN;ib[1]=_UDS_MSG_MONTH_ABBR_FEB;ib[2]=_UDS_MSG_MONTH_ABBR_MAR;ib[3]=_UDS_MSG_MONTH_ABBR_APR;ib[4]=_UDS_MSG_MONTH_ABBR_MAY;ib[5]=_UDS_MSG_MONTH_ABBR_JUN;ib[6]=_UDS_MSG_MONTH_ABBR_JUL;ib[7]=_UDS_MSG_MONTH_ABBR_AUG;ib[8]=_UDS_MSG_MONTH_ABBR_SEP;ib[9]=_UDS_MSG_MONTH_ABBR_OCT;ib[10]=_UDS_MSG_MONTH_ABBR_NOV;ib[11]=_UDS_MSG_MONTH_ABBR_DEC;R["month-abbr"]=ib;R.directions=_UDS_MSG_DIRECTIONS;
R["clear-results"]=_UDS_MSG_CLEAR_RESULTS;R["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;R["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;R["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;R.settings=_UDS_MSG_SETTINGS;R.search=_UDS_MSG_SEARCH;R["search-uc"]=_UDS_MSG_SEARCH_UC;R["powered-by"]=_UDS_MSG_POWERED_BY;R.sa=_UDS_MSG_SEARCHER_GSA;R.by=_UDS_MSG_SEARCHER_BY;R.code=_UDS_MSG_SEARCHER_CODE;R["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;R["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
R.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;la(R,_UDS_MSG_SEARCHCONTROL_NEXT);R["get-directions"]=_UDS_MSG_GET_DIRECTIONS;R["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;R["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;R["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;R["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;R["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;R["edit-tags"]=_UDS_MSG_EDIT_TAGS;R["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;R["search-string"]=_UDS_MSG_SEARCH_STRING;R["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
R["delete"]=_UDS_MSG_DELETE;R.deleted=_UDS_MSG_DELETED;R.cancel=_UDS_MSG_CANCEL;R["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;R["im-done"]=_UDS_MSG_IM_DONE_WATCHING;R["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;R["no-results"]=_UDS_MSG_NO_RESULTS;R["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;R.back=_UDS_MSG_BACK;R.subscribe=_UDS_MSG_SUBSCRIBE;R["us-pat"]="US Pat.";R["us-pat-app"]="US Pat. App";R["us-pat-filed"]="Filed";R.dym="Did you mean: ";function jb(a,c){var d=function(){};d.prototype=c[F];a.prototype=new d;a[F].Tj=function(c){var d=Array[F].splice[bb](arguments,[1,arguments[E]]);return c[bb](a,d)}}var _json_cache_defeater_=(new Date)[D](),_json_request_require_prep=!0;function kb(a,c){var d;if(d=lb("msie"))d="msie 6.0"in mb?mb["msie 6.0"]:mb["msie 6.0"]=ba.appVersion[gb]()[Ca]("msie 6.0")!=-1;d?k[Qa](S(this,nb,[a,c]),0):nb(a,c)}function ob(a){_json_request_require_prep=!1;kb(a,f);_json_request_require_prep=!0}
function nb(a,c){var d=m[Ka]("head")[0];d||(d=m[Xa][cb][s](m[A]("head")));var e=m[A]("script");ia(e,"text/javascript");e.charset="utf-8";var g=_json_request_require_prep?a+"&key="+google[L].ApiKey+"&v="+c:a;if(lb("msie")||lb("safari")||lb("konqueror"))g=g+"&nocache="+_json_cache_defeater_++;e.src=g;var i=function(){e.onload=f;e[cb][Ya](e);delete e};ba.product=="Gecko"?e.onload=i:e.onreadystatechange=function(a){a=(a?a:k[hb]).target?(a?a:k[hb]).target:(a?a:k[hb]).srcElement;if(a.readyState=="loaded"||
a.readyState=="complete")a.onreadystatechange=f,i()};d[s](e)}function pb(a,c){return function(){return c[bb](a,arguments)}}function S(a,c,d){return function(){return c[bb](a,d)}}function qb(a){for(;a[B];)a[Ya](a[B])}function rb(a,c){if(a)try{qb(a),a[s](c)}catch(d){}return c}function T(a,c){try{a[s](c)}catch(d){}return c}function sb(a){return m.createTextNode(a?a:"")}function U(a,c){var d=m[A]("div");a&&o(d,a);c&&r(d,c);return d}function tb(a,c){var d=m[A]("div");a&&T(d,sb(a));c&&r(d,c);return d}
function V(a){var c=m[A]("div");a&&r(c,a);return c}function ub(a,c){var d=m[A]("span");a&&T(d,sb(a));c&&r(d,c);return d}function vb(a,c,d){var e=m[A]("table");e[C]("cellSpacing",a?a:0);e[C]("cellPadding",c?c:0);d&&r(e,d);return e}function wb(a,c,d){(a=a.insertRow(-1))||alert(a);for(var e=0;e<c;e++)W(a,d);return a}function W(a,c){var d=a.insertCell(-1);c&&r(d,c);return d}function xb(a){var c=m[A]("td");a&&r(c,a);return c}
function yb(a,c,d,e){var g=m[A]("img");g.src=a;c&&ha(g,c);d&&qa(g,d);e&&r(g,e);return g}function zb(a,c,d,e,g){var i=m[A]("a");i.href=a;c&&(e?T(i,ub(c,e)):T(i,sb(c)));d&&ma(i,d);g&&ja(i,g);return i}function X(a,c,d,e,g){var i=U(f,e),l=m[A]("a");l.href=a;o(l,c);e&&r(l,e);d&&ma(l,d);g&&ja(l,g);i[s](l);return i}function Ab(a){var c=m[A]("form");a&&r(c,a);return c}function Bb(a,c){var d=m[A]("input");ia(d,"submit");q(d,a);c&&r(d,c);return d}
function Cb(a,c,d){var e=m[A]("input");e[C]("autoComplete","off");ia(e,"text");a==-1?Z(e,"util-css-expand"):e.size=a>0?a:10;c&&Z(e,c);d&&q(e,d);return e}function Db(a,c,d,e){var g=m[A]("input");ia(g,"checkbox");g.name=a;q(g,c);e&&r(g,e);d&&ka(g,d);return g}function Z(a,c){var d;a:{if(!(a==f||a[Na]==f)){d=a[Na][Sa](" ");for(var e=0;e<d[E];e++)if(d[e]==c){d=!0;break a}}d=!1}d||(a.className+=" "+c)}
function $(a,c){if(a[Na]!=f){for(var d=a[Na][Sa](" "),e=[],g=!1,i=0;i<d[E];i++)d[i]!=c?d[i]&&e[sa](d[i]):g=!0;g&&r(a,e[fb](" "))}}var Eb="",Fb={fj:{ak:1,ck:1,kk:1,id:1,lk:1,"in":1,mk:1,ok:1,pk:1,qk:1,rk:1,Ak:1,Mk:1,Qk:1,Rk:1,Uk:1,Vk:1,Xk:1},bk:{Uj:1,Wj:1,Xj:1,Yj:1,Zj:1,$j:1,fj:1,dk:1,"do":1,ek:1,fk:1,gk:1,hk:1,ik:1,jk:1,nk:1,sk:1,tk:1,uk:1,vk:1,wk:1,xk:1,yk:1,zk:1,Ck:1,Dk:1,Ek:1,Fk:1,Gk:1,Hk:1,Jk:1,Kk:1,Lk:1,Nk:1,Ok:1,Pk:1,Sk:1,Tk:1,Wk:1},Bk:{Vj:1}};
function lb(a){if(a in Gb)return Gb[a];return Gb[a]=ba.userAgent[gb]()[Ca](a)!=-1}var Gb={},mb={},Hb,Ib;k.Sj&&(Hb=!0,k.XMLHttpRequest&&(Ib=!0));function Jb(a){this.Id=a+"branding";this.Hc=a+"branding-vertical";this.Qj=a+"branding-img";this.Rj=a+"branding-user-defined";this.Qf=a+"branding-img-noclear";this.Jh=a+"branding-clickable";this.text=a+"branding-text"};var Kb=f,Lb=function(){if(Kb!=f)return Kb;var a=m[A]("div");ha(a[I],"1px");qa(a[I],"1px");a[I].border="1px solid black";a[I].padding="1px";a[I].visibility="hidden";m[Xa][s](a);var c=a[Aa];m[Xa][Ya](a);return Kb=c==5};function Nb(a){return da(a[w]("px",""))||0}
function Ob(a,c){typeof a=="string"&&(a=m[x](a));var d=m.defaultView||{},e=c?a.offsetHeight:a[Aa],g=c?["Top","Bottom"]:["Right","Left"],i;i=Lb()?["margin"]:["border","margin","padding"];var l=i[E],p=g[E];if(d&&d[Va])for(var u=d[Va](a,!1),d=0;d<l;d++)for(var z=0;z<p;z++)e+=Nb(u.getPropertyValue([i[d],g[z][gb]()][fb]("-")));else{u=a[Za];if(!Lb())for(z=0;z<p;z++)e+=Nb(u[["border",g[z],"Width"][fb]("")]);for(d=0;d<l;d++)if(i[d]!="border")for(z=0;z<p;z++)e+=Nb(u[[i[d],g[z]][fb]("")])}return e};google[J].a=function(){this.na=this.Gj=f;this.cf=!0;this.V={width:100,height:75};this.Ya=google[J].a.Mb;this.Yd=1;this.U(google[J].a.ga);this.ff();this.gwsUrl=this.w=this.M=this.Ij=this.z=this.Hj=this.Eb=this.eb=this.rd=this.mc=this.td=this.sd=f;this.Da=[];var a;if(typeof k==="object"&&k[Ua]&&k[Ua].hostname&&k[Ua].hostname!=""){if(Eb==""){var c=k[Ua].hostname[gb]()[Sa](".");c[E]<2&&(Eb=".com");a=c.pop();c=c.pop();Eb=a[E]==2?Fb[c]&&Fb[c][a]==1?"."+c+"."+a:"."+a:".com"}a=Eb}else a=".com";this.ef=a;
this.Ib=this.Hb=f};P("google.search.Search",google[J].a);google[J].a.Of=google[L][Ia];Q(google[J].a,"BASE",google[J].a.Of);google[J].a.Rh=/style=([^&]*)/;google[J].a.Ca="large";Q(google[J].a,"LARGE_RESULTSET",google[J].a.Ca);google[J].a.ga="small";Q(google[J].a,"SMALL_RESULTSET",google[J].a.ga);google[J].a.kb="filtered_cse";Q(google[J].a,"FILTERED_CSE_RESULTSET",google[J].a.kb);google[J].a.Xi=8;Q(google[J].a,"LARGE_RESULTS",google[J].a.Xi);google[J].a.aj=4;Q(google[J].a,"SMALL_RESULTS",google[J].a.aj);
google[J].a.Ri=10;Q(google[J].a,"FILTERED_CSE_RESULTS",google[J].a.Ri);google[J].a.$i="_top";Q(google[J].a,"LINK_TARGET_TOP",google[J].a.$i);google[J].a.Zi="_self";Q(google[J].a,"LINK_TARGET_SELF",google[J].a.Zi);google[J].a.Yi="_parent";Q(google[J].a,"LINK_TARGET_PARENT",google[J].a.Yi);google[J].a.Mb="_blank";Q(google[J].a,"LINK_TARGET_BLANK",google[J].a.Mb);google[J].a.dc="order-by-relevance";Q(google[J].a,"ORDER_BY_RELEVANCE",google[J].a.dc);google[J].a.Ja="order-by-date";
Q(google[J].a,"ORDER_BY_DATE",google[J].a.Ja);google[J].a.Sf="order-by-ascending-date";Q(google[J].a,"ORDER_BY_ASCENDING_DATE",google[J].a.Sf);google[J].a.uc="restrict-type";Q(google[J].a,"RESTRICT_TYPE",google[J].a.uc);google[J].a.jb="restrict-safesearch";Q(google[J].a,"RESTRICT_SAFESEARCH",google[J].a.jb);google[J].a.hd="active";Q(google[J].a,"SAFESEARCH_STRICT",google[J].a.hd);google[J].a.gd="off";Q(google[J].a,"SAFESEARCH_OFF",google[J].a.gd);google[J].a.Kf="moderate";
Q(google[J].a,"SAFESEARCH_MODERATE",google[J].a.Kf);google[J].a.nb="restrict-extended";Q(google[J].a,"RESTRICT_EXTENDED_ARGS",google[J].a.nb);google[J].a.Cj=R;Q(google[J].a,"strings",google[J].a.Cj);google[J].a.Mg=function(){if(google[J].LoadArgs){var a=fa(google[J].LoadArgs)[Da](google[J].a.Rh);if(a&&a[1])return a[1]}return f};google[J].a[F].xi=function(){var a=this.Ea+"?hl="+google[J][db]+"&source=uds";a+=this.w?this.w:"&q=";return this.Sa&&this.Sa!=""?this.Sa:a};
google[J].a[F].uj=function(a){this.M=a==f||a==""?f:a};Q(google[J].a[F],"setQueryAddition",google[J].a[F].uj);google[J].a[F].Pa=function(a,c,d){a=google[J].a.Of+this.Qa+"?callback="+a+"&context="+c+"&rsz="+this.Aa+"&hl="+google[J][db];this.rc&&(a+="&source="+h(this.rc));this.ef&&(a+="&gss="+this.ef);google[J].JSHash&&(a+="&sig="+google[J].JSHash);d&&(a+="&start="+d);return a};google[J].a[F].yj=function(a){this.rc=a};Q(google[J].a[F],"setSearcherSrc",google[J].a[F].yj);
google[J].a[F].Wb=function(a){this.Ya=a};Q(google[J].a[F],"setLinkTarget",google[J].a[F].Wb);O=google[J].a[F];O.u=function(){return this.Ya&&this.Ya!=""?this.Ya:f};O.jc=function(){if(this.sd==f)this.sd="gsc-"+this.z+"Result";return this.sd};O.Ia=function(){if(this.td==f)this.td="gs-"+this.z+"Result";return this.td};O.fh=function(){if(this.mc==f)this.mc=R[this.z];return this.eb?this.eb:this.mc};O.bh=function(){if(this.rd==f)this.rd=R[this.z];return this.eb?this.eb:this.rd};O.nj=function(){return this.Aa};
Q(google[J].a[F],"getResultSetSize",google[J].a[F].nj);google[J].a[F].U=function(a){if(a>0&&a<=8)this.Aa=a;else switch(a){case google[J].a.Ca:this.Aa=google[J].a.Ca;break;default:case google[J].a.ga:this.Aa=google[J].a.ga}};Q(google[J].a[F],"setResultSetSize",google[J].a[F].U);
pa(google[J].a[F],function(a){var c=(new Date)[D]();this.Qd=c%100==1?c:-1;c=this.ya(a);c+=this.Pb?"&"+this.Pb:"";k._googleudsextrastuff&&(c+=k._googleudsextrastuff);this.cursor=f;this.qf=a;kb(c,google[J][Oa]);if(this.Da&&this.Da[E]>0)for(c=0;c<this.Da[E];c++)this.Da[c][M](a)});Q(google[J].a[F],"execute",google[J].a[F][M]);google[J].a[F].Ef=function(a){if(this[H]&&a<this[H].pages[E])a=this.ya(this.qf,b,b,this[H].pages[a].start),this.cursor=f,kb(a,google[J][Oa])};Q(google[J].a[F],"gotoPage",google[J].a[F].Ef);
google[J].a[F].dj=function(a){this.Da&&this.Da[sa](a)};Q(google[J].a[F],"addRelatedSearcher",google[J].a[F].dj);google[J].a[F].mj=function(a,c,d){return this.ya(a,c,d)+"&key="+google[L].ApiKey+"&v="+google[J][Oa]};Q(google[J].a[F],"getExecuteUrl",google[J].a[F].mj);google[J].a[F].Ua=function(a){var c=X("http://code.google.com/apis/ajaxsearch/faq.html",R.watermark+" - "+this.gj(),"_blank","gs-watermark");T(a,c)};google[J].a[F].gj=function(){var a=new Date;return a.getMonth()+1+"/"+a.getFullYear()};
google[J].a[F].zb=function(a){var c;c=a.getFullYear();var d=a.getMonth(),e=R["month-abbr"][d],a=a.getDate();a<10&&(a="0"+a);switch(google[J].ShortDatePattern){case "MDY":c=e+" "+a+", "+c;break;case "YMD":google[J][db]=="zh-CN"||google[J][db]=="zh-TW"||google[J][db]=="ja"||google[J][db]=="ko"?(e=Pb[google[J][db]],c=c+e.year+(d+1)+e.month+a+e.day):c=c+" "+e+" "+a;break;default:case "DMY":c=a+" "+e+" "+c}return c};Q(google[J].a[F],"formatToShortDate",google[J].a[F].zb);
var Pb={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};google[J].a.Uf=36E5;google[J].a.Lh=6E4;google[J].a.Kh=864E5;
google[J].a[F].Md=function(a){var c=(new Date)[D](),d=a[D]();if(c<d)return R["n-minutes-ago"](2);c-=d;if(c<google[J].a.Uf)return a=n[ya](c/google[J].a.Lh),R["n-minutes-ago"](a<=1?2:a);if(c<google[J].a.Kh)return a=n[ya](c/google[J].a.Uf),a<=1?R["one-hour-ago"]:R["n-hours-ago"](a);return this.zb(a)};Q(google[J].a[F],"formatToRelativeDate",google[J].a[F].Md);google[J].a[F].ff=function(){this.Ik=this.gwsUrl=f;this.results=[]};Q(google[J].a[F],"clearResults",google[J].a[F].ff);
google[J].a[F].wi=function(){this.Ag&&this.Ag();if(this.Qd!=-1)google[L].recordStat("asa_"+this.z,"req."+((new Date)[D]()-this.Qd),!0),this.Qd=-1};
google[J].a[F].ca=function(a,c,d,e){this.gwsUrl=f;if(this.results&&this.results[E]>0)for(var g=0;g<this.results[E];g++)if(this.results[g].html){var i=this.results[g].html;Qb||(Qb=m[A]("DIV"));Qb[s](i);o(Qb,"")}a&&a.results&&a.results[E]>0?(this.results=a.results,a[H]&&a[H].moreResultsUrl?this.gwsUrl=this.Sa&&this.Sa!=""?this.Sa:a[H].moreResultsUrl:this.w&&this.Ea&&(this.gwsUrl=this.xi())):this.results=[];this.completionStatus=c;this.hashStatus=e;this.Mj=d;this.vg=a&&a.resultAttribution&&a.resultAttribution!=
f&&a.resultAttribution!=""?a.resultAttribution:f;a&&a[H]&&a[H].pages&&a[H].pages[E]>0?this.cursor=a[H]:typeof this[H]!="undefined"&&delete this[H];a&&a.context?this.context=a.context:typeof this.context!="undefined"&&delete this.context;a&&a.promotions?this.promotions=a.promotions:typeof this.promotions!="undefined"&&delete this.promotions;a&&a.omittedResults?this.omittedResults=a.omittedResults:typeof this.omittedResults!="undefined"&&delete this.omittedResults;a&&a.spelling?this.spelling=a.spelling:
typeof this.spelling!="undefined"&&delete this.spelling;this.cf&&this.vi();this.wi()};Q(google[J].a[F],"onSearchComplete",google[J].a[F].ca);google[J].a[F].ee=function(){var a=f;this.vg&&(a=U(this.vg,"gs-results-attribution"));return a};Q(google[J].a[F],"getAttribution",google[J].a[F].ee);google[J].a[F].vi=function(){var a,c;for(a=0;a<this.results[E];a++)c=this.results[a],this.K(c)};google[J].a[F].pb=function(a,c,d){d||(d=[f]);this.Ag=S(a,c,d)};Q(google[J].a[F],"setSearchCompleteCallback",google[J].a[F].pb);
google[J].a.oa=function(a,c){var d;if(a[E])for(var e=0;e<a[E];e++)if(a[e]==f){a[e]=c;d=e;break}d||(d=a[E],a[sa](c));return d};Q(google[J].a,"AllocateCompletionMapContext",google[J].a.oa);google[J].a[F].Kb=function(a){this.eb=a};Q(google[J].a[F],"setUserDefinedLabel",google[J].a[F].Kb);google[J].a[F].Aj=function(a){this.Eb=a};Q(google[J].a[F],"setUserDefinedClassSuffix",google[J].a[F].Aj);google[J].a[F].sj=function(){this.cf=!1};Q(google[J].a[F],"setNoHtmlGeneration",google[J].a[F].sj);
google[J].a.hb=function(a,c,d,e,g){var i=n.min(n.min(d[v]/a,d[eb]/c),1),l={};ha(l,n[wa](a*i));qa(l,n[wa](c*i));if(e&&(ha(e,l[v]),qa(e,l[eb]),g))e[I].left=(d[v]-l[v])/2+"px";return l};Q(google[J].a,"scaleImage",google[J].a.hb);google[J].a.Tf=1;Q(google[J].a,"VERTICAL_BRANDING",google[J].a.Tf);google[J].a.Si=2;Q(google[J].a,"HORIZONTAL_BRANDING",google[J].a.Si);
google[J].a.lj=function(a,c,d){var e=c&&c==google[J].a.Tf,g=new Jb("gsc-"),c=V(g.Id),i=vb(f,f,g.Id);T(c,i);e=!e;e||(Z(c,g.Hc),Z(i,g.Hc));var l=wb(i,0),p,u;e?u=p=l:(p=l,u=wb(i,0));var z="/css/small-logo.png",G=51,l=15;d&&typeof d=="string"&&d[Da](/^http:\/\/www\.youtube\.com/)&&(z="/css/youtube-logo-55x24.png",G=55,l=24,Z(c,g.Id+"-youtube"),e||(Z(c,g.Hc+"-youtube"),Z(i,g.Hc+"-youtube")));e=W(p,g.text);i=W(u,g.Qf);p=U(R["powered-by"],g.text);z=google[L][Ia]+z;u=g.Qf;Hb&&!Ib?(u=V(u),u[I].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+
z+'")',ha(u[I],G+"px"),qa(u[I],l+"px")):u=yb(z,f,f,u);l=u;T(e,p);if(d){e="http://www.google.com";if(typeof d=="string"&&(d[Da](/^http:\/\/[a-z]*\.google\.com/)||d[Da](/^http:\/\/www\.youtube\.com/)))e=d;d=zb(e,f,"_BLANK");r(d,g.Jh);T(d,l);T(i,d)}else T(i,l);a&&(a=typeof a=="string"?m[x](a):a,qb(a),T(a,c));return c};Q(google[J].a,"getBranding",google[J].a.lj);google[J].a.setOnLoadCallback=function(a,c){google.setOnLoadCallback(a,c)};Q(google[J].a,"setOnLoadCallback",google[J].a.setOnLoadCallback);
var Qb;google[J].a[F].Fg=function(a){var c=this.Hb;a&&(c=a);var a={},d=V(this.Ia());Z(d,"gs-result");Z(d,"gs-error-result");c=U(c,"gs-snippet");T(d,c);a.html=d;return a};google[J].a[F].Gg=function(a){var c=this.Ib;a&&(c=a);var a={},d=V(this.Ia());Z(d,"gs-result");Z(d,"gs-no-results-result");c=U(c,"gs-snippet");T(d,c);a.html=d;return a};j("google.search.CurrentLocale",ea);j("google.search.ShortDatePattern",aa);google[J].s=function(){google[J].a[K](this);this.z="blog";this.Qa="/GblogSearch";this.Ea="http://blogsearch.google.com/blogsearch";this.l=f;this.X=!1;this.ob=!0;this.na=pb(this,google[J].s[F].Fa);this.ib="gsc-blogConfig";this.p=f};P("google.search.BlogSearch",google[J].s);jb(google[J].s,google[J].a);google[J].s.J="GblogSearch";Q(google[J].s,"RESULT_CLASS",google[J].s.J);google[J].s.n=[];google[J].s.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].s.n[i];google[J].s.n[i]=f;a.ca(c,d,e,g)};
Q(google[J].s,"RawCompletion",google[J].s.P);google[J].s[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].s.n,this):d;c=this.Pa(c==f?"google.search.BlogSearch.RawCompletion":c,d,e);this.M&&(a=a+" "+this.M);this.l&&(a=a+" blogurl:"+this.l);a="&q="+h(a);this.X&&(a+="&scoring=d");c+=a;this.w=a;return c};
google[J].s[F].K=function(a){a.html&&delete a.html;var c=V(this.Ia());Z(c,"gs-result");var d;d=X(a.postUrl,a[Ma],this.u(),"gs-title");T(c,d);d=new Date(a.publishedDate);d=U(this.zb(d),"gs-publishedDate");T(c,d);d=new Date(a.publishedDate);d=U(this.Md(d),"gs-relativePublishedDate");T(c,d);d=U(a[za],"gs-snippet");T(c,d);d=X(a.blogUrl,a.blogUrl,this.u(),"gs-visibleUrl");T(c,d);a.html=c;this.Ua(a.html)};Q(google[J].s[F],"createResultHtml",google[J].s[F].K);
google[J].s[F].Ba=function(a){this.l=a==f||a==""?f:a};Q(google[J].s[F],"setSiteRestriction",google[J].s[F].Ba);google[J].s[F].S=function(a){this.X=a==google[J].a.Ja?!0:!1};Q(google[J].s[F],"setResultOrder",google[J].s[F].S);
google[J].s[F].Fa=function(a,c){if(c){if(this.p==f){var d=V("gsc-configSetting");this.p=Db(f,"0",this.X,"gsc-configSettingCheckbox");T(d,this.p);T(d,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,Bb(R[Wa],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.p,this.X);this.p[Ea]()}else this.p&&(this.p[Pa]?this.S(google[J].a.Ja):this.S(google[J].a.dc))};google[J].m=function(){google[J].a[K](this);this.z="book";this.Qa="/GbookSearch";this.Ea="http://books.google.com/books";this.vc=!1;this.qd=f};P("google.search.BookSearch",google[J].m);jb(google[J].m,google[J].a);google[J].m.J="GbookSearch";Q(google[J].m,"RESULT_CLASS",google[J].m.J);google[J].m.If="user-list";Q(google[J].m,"USER_LIST",google[J].m.If);google[J].m.Gf=1;Q(google[J].m,"TYPE_ALL_BOOKS",google[J].m.Gf);google[J].m.Hf=2;Q(google[J].m,"TYPE_FULL_VIEW_BOOKS",google[J].m.Hf);
google[J].m.n=[];google[J].m.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].m.n[i];google[J].m.n[i]=f;a.ca(c,d,e,g)};Q(google[J].m,"RawCompletion",google[J].m.P);google[J].m[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].m.n,this):d;c=this.Pa(c==f?"google.search.BookSearch.RawCompletion":c,d,e);this.M&&(a=a+" "+this.M);a="&q="+h(a);this.vc&&(a+="&as_brr=1");this.qd&&(a=a+"&as_list="+this.qd);c+=a;this.w=a;return c};
google[J].m[F].K=function(a){a.html&&delete a.html;a.thumbnailHtml=this.Rd(a);var c=V(this.Ia());Z(c,"gs-result");var d=V("gs-text-box"),e=vb(),g=wb(e,0),i=W(g,"gs-image-box"),g=W(g,"gs-text-box");T(i,a.thumbnailHtml[Ga](!0));T(g,d);T(c,e);e=X(a.unescapedUrl,a[Ma],this.u(),"gs-title");T(d,e);e=U(R.by+"&nbsp;"+a.authors,"gs-author");T(d,e);e=V("gs-spacer");T(d,e);a.publishedYear&&(e=U(a.publishedYear,"gs-publishedDate"),T(d,e));ca(a.pageCount,10)>0&&(e=U("-&nbsp;"+R["page-count"](a.pageCount),"gs-pageCount"),
T(d,e));e=X("http://books.google.com","books.google.com",this.u(),"gs-visibleUrl");T(d,e);a.html=c;this.Ua(a.html)};Q(google[J].m[F],"createResultHtml",google[J].m[F].K);
google[J].m[F].Rd=function(a){var c=V("gs-image-box gs-book-image-box"),d=V("gs-row-1"),e=yb("http://books.google.com/googlebooks/pages-trans.gif",f,f,"gs-pages");T(d,e);e=yb("http://books.google.com/googlebooks/p_edge-trans.gif",f,f,"gs-page-edge");T(d,e);T(c,d);d=V("gs-row-2");e=google[J].a.hb(a.tbWidth,a.tbHeight,this.V);e=yb(a.tbUrl,e[v],e[eb],"gs-image");a=zb(a.unescapedUrl,f,this.u(),"gs-image");r(a,"gs-image");T(a,e);T(d,a);T(c,d);return c};
google[J].m[F].Y=function(a,c){if(a==google[J].a.uc)c?c==google[J].m.Gf?this.vc=!1:c==google[J].m.Hf?this.vc=!0:this.Y(a,f):this.vc=!1;else if(a==google[J].m.If)this.qd=c&&c[Da](/^[a-zA-Z0-9\-_]*$/)?c:f};Q(google[J].m[F],"setRestriction",google[J].m[F].Y);google[J].c=function(){google[J].a[K](this);this.Yd=2;this.z="image";this.Qa="/GimageSearch";this.Ea="http://images.google.com/images";this.l=this.ed=this.$c=this.dd=this.bd=this.ad=this.cd=this.ma=f;this.V={width:112,height:84}};P("google.search.ImageSearch",google[J].c);jb(google[J].c,google[J].a);google[J].c.J="GimageSearch";Q(google[J].c,"RESULT_CLASS",google[J].c.J);google[J].c.Re="restrict-imagesize";Q(google[J].c,"RESTRICT_IMAGESIZE",google[J].c.Re);google[J].c.Wi=["icon"];
Q(google[J].c,"IMAGESIZE_SMALL",google[J].c.Wi);google[J].c.Vi=["small","medium","large","xlarge"];Q(google[J].c,"IMAGESIZE_MEDIUM",google[J].c.Vi);google[J].c.Ui=["xxlarge"];Q(google[J].c,"IMAGESIZE_LARGE",google[J].c.Ui);google[J].c.Ti=["huge"];Q(google[J].c,"IMAGESIZE_EXTRA_LARGE",google[J].c.Ti);google[J].c.Pe="restrict-coloration";Q(google[J].c,"RESTRICT_COLORIZATION",google[J].c.Pe);google[J].c.qe="mono";Q(google[J].c,"COLORIZATION_BLACK_AND_WHITE",google[J].c.qe);google[J].c.se="gray";
Q(google[J].c,"COLORIZATION_GRAYSCALE",google[J].c.se);google[J].c.re="color";Q(google[J].c,"COLORIZATION_COLOR",google[J].c.re);google[J].c.Oe="restrict-colorfilter";Q(google[J].c,"RESTRICT_COLORFILTER",google[J].c.Oe);google[J].c.Be="red";Q(google[J].c,"COLOR_RED",google[J].c.Be);google[J].c.ye="orange";Q(google[J].c,"COLOR_ORANGE",google[J].c.ye);google[J].c.Ee="yellow";Q(google[J].c,"COLOR_YELLOW",google[J].c.Ee);google[J].c.xe="green";Q(google[J].c,"COLOR_GREEN",google[J].c.xe);
google[J].c.Ce="teal";Q(google[J].c,"COLOR_TEAL",google[J].c.Ce);google[J].c.ue="blue";Q(google[J].c,"COLOR_BLUE",google[J].c.ue);google[J].c.Ae="purple";Q(google[J].c,"COLOR_PURPLE",google[J].c.Ae);google[J].c.ze="pink";Q(google[J].c,"COLOR_PINK",google[J].c.ze);google[J].c.De="white";Q(google[J].c,"COLOR_WHITE",google[J].c.De);google[J].c.we="gray";Q(google[J].c,"COLOR_GRAY",google[J].c.we);google[J].c.te="black";Q(google[J].c,"COLOR_BLACK",google[J].c.te);google[J].c.ve="brown";
Q(google[J].c,"COLOR_BROWN",google[J].c.ve);google[J].c.Qe="restrict-filetype";Q(google[J].c,"RESTRICT_FILETYPE",google[J].c.Qe);google[J].c.He="jpg";Q(google[J].c,"FILETYPE_JPG",google[J].c.He);google[J].c.Ie="png";Q(google[J].c,"FILETYPE_PNG",google[J].c.Ie);google[J].c.Ge="gif";Q(google[J].c,"FILETYPE_GIF",google[J].c.Ge);google[J].c.Fe="bmp";Q(google[J].c,"FILETYPE_BMP",google[J].c.Fe);google[J].c.Se="restrict-imagetype";Q(google[J].c,"RESTRICT_IMAGETYPE",google[J].c.Se);google[J].c.Ke="face";
Q(google[J].c,"IMAGETYPE_FACES",google[J].c.Ke);google[J].c.Je="clipart";Q(google[J].c,"IMAGETYPE_CLIPART",google[J].c.Je);google[J].c.Le="lineart";Q(google[J].c,"IMAGETYPE_LINEART",google[J].c.Le);google[J].c.Me="news";Q(google[J].c,"IMAGETYPE_NEWS",google[J].c.Me);google[J].c.Ne="photo";Q(google[J].c,"IMAGETYPE_PHOTO",google[J].c.Ne);google[J].c.Te="restrict-rights";Q(google[J].c,"RESTRICT_RIGHTS",google[J].c.Te);google[J].c.Xe="(cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial|cc_nonderived)";
Q(google[J].c,"RIGHTS_REUSE",google[J].c.Xe);google[J].c.Ve="(cc_publicdomain|cc_attribute|cc_sharealike|cc_nonderived).-(cc_noncommercial)";Q(google[J].c,"RIGHTS_COMMERCIAL_REUSE",google[J].c.Ve);google[J].c.We="(cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial).-(cc_nonderived)";Q(google[J].c,"RIGHTS_MODIFICATION",google[J].c.We);google[J].c.Ue="(cc_publicdomain|cc_attribute|cc_sharealike).-(cc_noncommercial|cc_nonderived)";Q(google[J].c,"RIGHTS_COMMERCIAL_MODIFICATION",google[J].c.Ue);
google[J].c.n=[];google[J].c.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].c.n[i];google[J].c.n[i]=f;a.ca(c,d,e,g)};Q(google[J].c,"RawCompletion",google[J].c.P);
google[J].c[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].c.n,this):d;c=this.Pa(c==f?"google.search.ImageSearch.RawCompletion":c,d,e);this.M&&(a=a+" "+this.M);a="&q="+h(a);this.ma&&(a=a+"&safe="+this.ma);this.cd&&(a=a+"&imgsz="+h(this.cd));this.ad&&(a=a+"&imgc="+h(this.ad));this.bd&&(a=a+"&imgcolor="+h(this.bd));this.dd&&(a=a+"&imgtype="+h(this.dd));this.$c&&(a=a+"&as_filetype="+h(this.$c));this.ed&&(a=a+"&as_rights="+h(this.ed));this.l&&(a=a+"&as_sitesearch="+h(this.l));c+=a;this.w=a;if(e&&
e!=0)this.w=this.w+"&start="+e;return c};
google[J].c[F].K=function(a){a.html&&delete a.html;var c=V(this.Ia());Z(c,"gs-result");var d=V("gs-image-box"),e=google[J].a.hb(a.tbWidth,a.tbHeight,this.V),g=yb(a.tbUrl,e[v],e[eb],"gs-image");g[I].left=(this.V[v]-e[v])/2+"px";ja(g,a.titleNoFormatting+" ("+a.visibleUrl+")");e=zb(a.unescapedUrl,f,this.u(),"gs-image");r(e,"gs-image");T(e,g);T(d,e);T(c,d);d=V("gs-text-box");g=U(a[za],"gs-snippet");ja(g,a.contentNoFormatting);T(d,g);g=U(a[v]+" x "+a[eb],"gs-size");T(d,g);g=X(a.originalContextUrl,a.visibleUrl,
this.u(),"gs-visibleUrl");ja(g,a.visibleUrl);T(d,g);T(c,d);a.html=c;this.Ua(a.html)};Q(google[J].c[F],"createResultHtml",google[J].c[F].K);google[J].c[F].Ba=function(a){this.l=a};Q(google[J].c[F],"setSiteRestriction",google[J].c[F].Ba);
google[J].c[F].Y=function(a,c){if(a==google[J].a.jb)this.ma=c?c==google[J].a.hd||c==google[J].a.gd?c:f:f;else if(a==google[J].c.Re)this.cd=c?c[fb]("|"):f;else if(a==google[J].c.Pe)this.ad=c?c==google[J].c.qe||c==google[J].c.se||c==google[J].c.re?c:f:f;else if(a==google[J].c.Oe)this.bd=c?c==google[J].c.Be||c==google[J].c.ye||c==google[J].c.Ee||c==google[J].c.xe||c==google[J].c.Ce||c==google[J].c.ue||c==google[J].c.Ae||c==google[J].c.ze||c==google[J].c.De||c==google[J].c.we||c==google[J].c.te||c==google[J].c.ve?
c:f:f;else if(a==google[J].c.Qe)this.$c=c?c==google[J].c.He||c==google[J].c.Ie||c==google[J].c.Ge||c==google[J].c.Fe?c:f:f;else if(a==google[J].c.Se)this.dd=c?c==google[J].c.Ke||c==google[J].c.Je||c==google[J].c.Le||c==google[J].c.Me||c==google[J].c.Ne?c:f:f;else if(a==google[J].c.Te)this.ed=c?c==google[J].c.Xe||c==google[J].c.Ve||c==google[J].c.We||c==google[J].c.Ue?c:f:f};Q(google[J].c[F],"setRestriction",google[J].c[F].Y);google[J].f=function(){google[J].a[K](this);this.la=f;this.ka="San Francisco, CA";this.ra={y:37.77916,x:-122.42009};this.tb=f;this.Vb=!0;this.Ub=!1;this.ub=f;this.ob=!0;this.na=pb(this,this.Fa);this.ib="gsc-locationConfig";this.z="local";this.Qa="/GlocalSearch";this.Ea="http://www.google.com/local";this.xb=this.N=f};P("google.search.LocalSearch",google[J].f);jb(google[J].f,google[J].a);google[J].f.J="GlocalSearch";Q(google[J].f,"RESULT_CLASS",google[J].f.J);google[J].f.Bf="blended";
Q(google[J].f,"TYPE_BLENDED_RESULTS",google[J].f.Bf);google[J].f.Cf="kmlonly";Q(google[J].f,"TYPE_KMLONLY_RESULTS",google[J].f.Cf);google[J].f.Df="localonly";Q(google[J].f,"TYPE_LOCALONLY_RESULTS",google[J].f.Df);google[J].f.ng="disabled";Q(google[J].f,"ADDRESS_LOOKUP_DISABLED",google[J].f.ng);google[J].f.og="enabled";Q(google[J].f,"ADDRESS_LOOKUP_ENABLED",google[J].f.og);google[J].f.sg=0;Q(google[J].f,"STATIC_MAP_ZOOM_FARTHEST",google[J].f.sg);google[J].f.bj=13;
Q(google[J].f,"STATIC_MAP_ZOOM_DEFAULT",google[J].f.bj);google[J].f.rg=21;Q(google[J].f,"STATIC_MAP_ZOOM_CLOSEST",google[J].f.rg);google[J].f.Nd=8;Q(google[J].f,"STATIC_MAP_MAX_POINTS",google[J].f.Nd);google[J].f.ti=3.141592653589;google[J].f.si=6367E3;google[J].f.ui=16093;google[J].f.n=[];google[J].f.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].f.n[i];google[J].f.n[i]=f;a.resultViewport=c&&c.viewport?c.viewport:f;a.ca(c,d,e,g)};Q(google[J].f,"RawCompletion",google[J].f.P);
google[J].f[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].f.n,this):d;c=this.Pa(c==f?"google.search.LocalSearch.RawCompletion":c,d,e);e="";e="&q="+h(a);c+=e;this.viewport=f;if(this.la){var g;this.Vb?(d=this.la.getCenterLatLng(),g=this.la.getSpanLatLng(),a="&sll="+d.y+","+d.x,a+="&sspn="+g[eb]+","+g[v]):(d=this.la.getCenter(),g=this.la.getBounds().toSpan().toUrlValue(),a="&sll="+d.y+","+d.x,a+="&sspn="+g);a+=google[J].f.pd(d.y,d.x);c+=a;e+=a}else this.ra?(a="&sll="+this.ra.y+","+this.ra.x,
this.tb&&(a=a+"&sspn="+this.tb.lat+","+this.tb.lng),a+=google[J].f.pd(this.ra.y,this.ra.x),c+=a,e+=a):this.ka&&(a="&near="+h(this.ka),c+=a,e+=a);this.Ub&&(c+="&nogeocode=t",e+="&nogeocode=t");this.ub&&(c+="&mrt="+h(this.ub),e+="&mrt="+h(this.ub));if(e)this.w=e;return c};google[J].f.pd=function(a,c){var d=2*google[J].f.ui/google[J].f.si*2*google[J].f.ti;return"&gll="+n[ya]((a-d)*1E6)+","+n[ya]((c-d)*1E6)+","+n[ya]((a+d)*1E6)+","+n[ya]((c+d)*1E6)+"&llsep=500,500"};Q(google[J].f,"centerToGll",google[J].f.pd);
google[J].f[F].K=function(a){a.html&&delete a.html;var c=V(this.Ia());Z(c,"gs-result");var d;d=X(a.url,a[Ma],this.u(),"gs-title");T(c,d);a.listingType=="kml"&&a[za]&&a[za]!=""&&(d=U(a[za],"gs-snippet"),T(c,d));var e=V("gs-address");if(a.addressLines&&a.addressLines[E]>0)for(var g=0;g<a.addressLines[E];g++){d=a.addressLines[g];var i="gs-addressLine";g==0?i="gs-street gs-addressLine":g==1&&(i="gs-city gs-addressLine");d=U(d,i);T(e,d)}else{d=U(a.streetAddress,"gs-street");T(e,d);g="";if(a.city!="")g=
a.city,a.region!=""&&(g+=", ");d=U(g,"gs-city");T(e,d);d=U(a.region,"gs-region");T(e,d)}d=U(a.country,"gs-country");T(e,d);T(c,e);if(a.phoneNumbers&&a.phoneNumbers[E]){g=e=f;d=a.phoneNumbers[0];for(var l=0;l<a.phoneNumbers[E];l++){i=a.phoneNumbers[l];if(i[Ha]=="main"){e=i;break}if(i[Ha]==""||i[Ha]=="mobile"&&g==f)g=i}d=U((e?e:g?g:d).number,"gs-phone");T(c,d)}a.ddUrl&&a.ddUrl!=""&&(d=X(a.ddUrl,R.directions,this.u(),"gs-directions"),T(c,d));a.ddUrlToHere&&a.ddUrlToHere!=""&&a.ddUrlFromHere&&a.ddUrlFromHere!=
""&&(d=V("gs-directions-to-from"),e=U(R["get-directions"]+":","gs-label"),d[s](e),e=X(a.ddUrlToHere,R["to-here"],this.u(),"gs-secondary-link"),d[s](e),e=U("-","gs-spacer"),d[s](e),e=X(a.ddUrlFromHere,R["from-here"],this.u(),"gs-secondary-link"),d[s](e),T(c,d));a.html=c;this.Ua(a.html)};Q(google[J].f[F],"createResultHtml",google[J].f[F].K);
google[J].f[F].ug=function(a){if(a.centerAndZoom){if(this.Vb=!0,this.la=a,this.ra=f,this.ka="",this.N)this.N=f}else if(a.setCenter){if(this.Vb=!1,this.la=a,this.tb=this.ra=f,this.ka="",this.N)this.N=f}else if(a.x&&a.y){if(this.Vb=!0,this.ra=a,this.la=this.tb=f,this.ka="",this.N)this.N=f}else if(a!=f&&a!=""){this.Vb=!0;this.la=f;this.ka=a;this.ra=f;if(this.N)this.N=f;var c=new google[J].f;c.pb(this,this.ii,[c,a]);c[M](a)}};Q(google[J].f[F],"setCenterPoint",google[J].f[F].ug);
google[J].f[F].ii=function(a,c){if(a.results&&a.results[E]){var d={};d.y=da(a.results[0].lat);d.x=da(a.results[0].lng);this.ra=d;this.ka=c;this.ob=!0;this.la=f;if(a.resultViewport)d={},d.Nj=da(a.resultViewport.span.lat)/2,d.Oj=da(a.resultViewport.span.lng)/2,this.tb=d}};
google[J].f[F].Fa=function(a,c){if(c){if(this.N==f){var d=f;if(this.la==f){var e=V("gsc-configSetting");this.N=Cb(f,"gsc-configSettingInput",this.ka==""?f:this.ka);T(e,U(R["search-location"],"gsc-configSettingInputLabel"));T(e,this.N);T(a,e);d=this.N}e=V("gsc-configSetting");this.xb=Db(f,"0",this.Ub,"gsc-configSettingCheckbox");T(e,this.xb);T(e,U(R["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(d==f)d=this.xb;var g=U(f,"gsc-configSettingSubmit");T(g,Bb(R[Wa],"gsc-configSettingSubmit"));
T(e,g);T(a,e);d[Ea]()}}else{if(this.N){if(this.N[y])this.ka=this.N[y],this.ug(this.ka);this.N=f}if(this.xb)this.Ub=this.xb[Pa],this.xb=f;qb(a)}};google[J].f[F].oj=function(a){if(a==google[J].f.ng)this.Ub=!0;else if(a==google[J].f.og)this.Ub=!1};Q(google[J].f[F],"setAddressLookupMode",google[J].f[F].oj);google[J].f.qg=function(a,c,d,e){var g=a.staticMapUrl,g=g[w](/&size=\d*x\d*/,"&size="+d+"x"+c);e&&e<=google[J].f.rg&&e>=google[J].f.sg&&(g=g[w](/&zoom=\d*/,"&zoom="+e));return a.staticMapUrl=g};
Q(google[J].f,"resizeStaticMapUrl",google[J].f.qg);
google[J].f.hj=function(a,c,d,e){var g="",i={staticMapUrl:"http://maps.google.com/maps/api/staticmap?maptype=roadmap&size=150x100&zoom=13&format=gif&sensor=false"},c=google[J].f.qg(i,c,d,e);e==f&&(c=c[w](/&zoom=\d*/,""));e=a[E];if(e>google[J].f.Nd)e=google[J].f.Nd;for(d=0;d<e;d++){var l;l=a[d];if(l.lat&&l.lng)typeof l.lat=="string"?(i=da(l.lat),l=da(l.lng)):(i=l.lat,l=l.lng);else if(l.x&&l.y)i=l.y,l=l.x;else return f;i="&markers=__ICONID____LAT__,__LNG__"[w](/__LAT__/,i);i=i[w](/__LNG__/,l);l=65+
d;i=e>1?i[w](/__ICONID__/,"label:"+String.fromCharCode(l)+"|"):i[w](/__ICONID__/,"");g+=i}return c+g};Q(google[J].f,"computeStaticMapUrl",google[J].f.hj);google[J].f[F].Y=function(a,c){if(a==google[J].a.uc)c?(this.ub=f,this.ub=c==google[J].f.Bf||c==google[J].f.Cf||c==google[J].f.Df?c:f):this.ub=f};Q(google[J].f[F],"setRestriction",google[J].f[F].Y);google[J].o=function(){google[J].a[K](this);this.z="news";this.Qa="/GnewsSearch";this.Ea="http://news.google.com/nwshp";this.Jj=f;this.vb="site:";this.X=!1;this.ob=!0;this.na=pb(this,this.Fa);this.ib="gsc-newsConfig";this.C=this.p=f};P("google.search.NewsSearch",google[J].o);jb(google[J].o,google[J].a);google[J].o.J="GnewsSearch";Q(google[J].o,"RESULT_CLASS",google[J].o.J);google[J].o.pg="GnewsSearch.quote";Q(google[J].o,"QUOTE_RESULT_CLASS",google[J].o.pg);google[J].o.n=[];
google[J].o.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].o.n[i];google[J].o.n[i]=f;a.ca(c,d,e,g)};Q(google[J].o,"RawCompletion",google[J].o.P);
google[J].o[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].o.n,this):d;c=this.Pa(c==f?"google.search.NewsSearch.RawCompletion":c,d,e);d=f;a&&(d=a);this.M&&(d=d==f?this.M:d+" "+this.M);this.l&&(d=d==f?this.vb+this.l:d+" "+this.vb+this.l);a=d?"&q="+h(d):"";this.X&&(a+="&scoring=d");if(this.C){var d="",g;for(g in this.C)g.charAt(0)==":"&&(d+="&"+this.C[g]);a+=d}this.l&&this.vb=="source:"&&(c=c[w](/&hl=.*&/,"&hl=en&"));c+=a;this.w=a;if(e&&e!=0)this.w=this.w+"&start="+e;return c};
google[J].o[F].K=function(a){a.html&&delete a.html;if(a.GsearchResultClass!=google[J].o.pg){var c=V(this.Ia());Z(c,"gs-result");var d;d=X(a.unescapedUrl,a[Ma],this.u(),"gs-title");T(c,d);d=U(a.publisher,"gs-publisher");T(c,d);d=a[Ua][Sa](",");d[E]>1&&(d=U(", "+d[d[E]-1],"gs-location"),T(c,d));d=new Date(a.publishedDate);d=U(" - "+this.zb(d),"gs-publishedDate");T(c,d);d=new Date(a.publishedDate);d=U(" - "+this.Md(d),"gs-relativePublishedDate");T(c,d);d=U(a[za],"gs-snippet");T(c,d);a.clusterUrl&&a.clusterUrl!=
""&&(d=X(a.clusterUrl,R["related-articles"]+"&nbsp;&raquo;",this.u(),"gs-clusterUrl"),T(c,d));a.html=c;this.Ua(a.html)}};Q(google[J].o[F],"createResultHtml",google[J].o[F].K);google[J].o[F].Ba=function(a){a==f||a==""?(this.l=f,this.vb="site:"):a[Da]("[./:]")?(this.vb="site:",this.l=a):(this.vb="source:",this.l=a[w](/\s/g,"_"))};Q(google[J].o[F],"setSiteRestriction",google[J].o[F].Ba);google[J].o[F].S=function(a){this.X=a==google[J].a.Ja?!0:!1};Q(google[J].o[F],"setResultOrder",google[J].o[F].S);
google[J].o[F].Fa=function(a,c){if(c){if(this.p==f){var d=V("gsc-configSetting");this.p=Db(f,"0",this.X,"gsc-configSettingCheckbox");T(d,this.p);T(d,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,Bb(R[Wa],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.p,this.X);this.p[Ea]()}else this.p&&(this.p[Pa]?this.S(google[J].a.Ja):this.S(google[J].a.dc))};
google[J].o[F].Ih={geo:!0,qsid:!0,quotesearch:!0,topic:!0,ned:!0,scoring:!0,as_mind:!0,as_minm:!0,as_miny:!0,as_maxd:!0,as_maxm:!0,as_maxy:!0};google[J].o[F].Y=function(a,c){if(a==google[J].a.nb)if(c)for(var d in c){var e=c[d];if(typeof this.Ih[d]!="undefined")this.C=this.C||{},this.C[":"+d]=d+"="+h(e)}else this.C=f};Q(google[J].o[F],"setRestriction",google[J].o[F].Y);google[J].j=function(){google[J].a[K](this);this.z="patent";this.Qa="/GpatentSearch";this.Ea="http://www.google.com/patents";this.af="";this.Xb=f;this.ob=!0;this.na=pb(this,this.Fa);this.ib="gsc-patentConfig";this.p=f};P("google.search.PatentSearch",google[J].j);jb(google[J].j,google[J].a);google[J].j.J="GpatentSearch";Q(google[J].j,"RESULT_CLASS",google[J].j.J);google[J].j.Lf=1;Q(google[J].j,"TYPE_ANY_STATUS",google[J].j.Lf);google[J].j.Nf=2;Q(google[J].j,"TYPE_ISSUED_PATENTS",google[J].j.Nf);
google[J].j.Mf=3;Q(google[J].j,"TYPE_APPLICATIONS",google[J].j.Mf);google[J].j.n=[];google[J].j.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].j.n[i];google[J].j.n[i]=f;a.ca(c,d,e,g)};Q(google[J].j,"RawCompletion",google[J].j.P);google[J].j[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].j.n,this):d;c=this.Pa(c==f?"google.search.PatentSearch.RawCompletion":c,d,e);this.M&&(a=a+" "+this.M);a="&q="+h(a)+this.af;this.Xb&&(a+=this.Xb);c+=a;this.w=a;return c};
google[J].j[F].K=function(a){a.html&&delete a.html;a.thumbnailHtml=this.Rd(a);var c=V(this.Ia());Z(c,"gs-result");var d=V("gs-text-box"),e=vb(),g=wb(e,0),i=W(g,"gs-image-box"),g=W(g,"gs-text-box");T(i,a.thumbnailHtml[Ga](!0));T(g,d);T(c,e);i=X(a.unescapedUrl,a[Ma],this.u(),"gs-title");T(d,i);e=V("gs-patent-info gs-metadata");T(d,e);i=f;i=a.patentNumber?a.patentStatus=="issued"?R["us-pat"]+"&nbsp;"+a.patentNumber:R["us-pat-app"]+"&nbsp;"+a.patentNumber:R["us-pat-app"]+"&nbsp; N/A";i=U(i,"gs-patent-number");
T(e,i);a.applicationDate&&(i=U(" - "+this.zb(new Date(a.applicationDate)),"gs-publishedDate"),T(e,i));a.assignee&&(i=U(" - "+a.assignee,"gs-author"),T(e,i));i=U(a[za],"gs-snippet");T(d,i);T(d,i);a.html=c;this.Ua(a.html)};Q(google[J].j[F],"createResultHtml",google[J].j[F].K);google[J].j[F].Rd=function(a){var c=V("gs-patent-image"),d=yb(a.tbUrl,75,100,"gs-image"),a=zb(a.unescapedUrl,f,this.u(),"gs-image");r(a,"gs-image");T(a,d);T(c,a);return c};
google[J].j[F].S=function(a){this.Xb=a==google[J].a.Ja?"&scoring=d":a==google[J].a.Sf?"&scoring=ad":f};Q(google[J].j[F],"setResultOrder",google[J].j[F].S);google[J].j[F].Y=function(a,c){if(a==google[J].a.uc)this.af=c?c==google[J].j.Lf?"":c==google[J].j.Nf?"&as_psrg=1":c==google[J].j.Mf?"&as_psra=1":"":""};Q(google[J].j[F],"setRestriction",google[J].j[F].Y);
google[J].j[F].Fa=function(a,c){if(c){var d=!1;this.Xb&&this.Xb=="&scoring=d"&&(d=!0);if(this.p==f){var e=V("gsc-configSetting");this.p=Db(f,"0",d,"gsc-configSettingCheckbox");T(e,this.p);T(e,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));d=V("gsc-configSettingSubmit");T(d,Bb(R[Wa],"gsc-configSettingSubmit"));T(e,d);T(a,e)}else ka(this.p,d);this.p[Ea]()}else this.p&&(this.p[Pa]?this.S(google[J].a.Ja):this.S(google[J].a.dc))};google[J].H=function(){this.ae=this.fa=google[J].b.Xa;ra(this,f);this.V={width:112,height:84};this.kc={width:100,height:75};this.Ib=f};P("google.search.SearcherOptions",google[J].H);google[J].H[F].df=function(a){switch(a){case google[J].b.Xf:case google[J].b.fb:case google[J].b.Xa:this.fa=a;break;default:this.fa=google[J].b.Xa}this.ae=this.fa};Q(google[J].H[F],"setExpandMode",google[J].H[F].df);google[J].H[F].vj=function(a){qb(a);ra(this,a)};Q(google[J].H[F],"setRoot",google[J].H[F].vj);
google[J].H[F].Rb=function(a){this.Ib=a};Q(google[J].H[F],"setNoResultsString",google[J].H[F].Rb);google[J].H[F].qj=function(a){a>100&&(a=100);qa(this.V,a);ha(this.V,n[wa](a*1.33))};Q(google[J].H[F],"setImageResultsTbHeight",google[J].H[F].qj);google[J].H[F].Bj=function(a){a>100&&(a=100);qa(this.kc,a);ha(this.kc,n[wa](a*1.33))};Q(google[J].H[F],"setVideoResultsTbHeight",google[J].H[F].Bj);google[J].A=function(){ga(this,f);this.Ye=f;this.T=google[J].b.Oa;this.of=!1;this.Z=f};
P("google.search.DrawOptions",google[J].A);google[J].A[F].nf=function(a){ga(this,a)};Q(google[J].A[F],"setInput",google[J].A[F].nf);google[J].A[F].wj=function(a){a&&typeof a=="string"&&(a=m[x](a));this.Ye=a};Q(google[J].A[F],"setSearchFormRoot",google[J].A[F].wj);google[J].A[F].Af=function(a){this.T=a==google[J].b.Oa||a==google[J].b.za?a:google[J].b.Oa};Q(google[J].A[F],"setDrawMode",google[J].A[F].Af);google[J].A[F].pj=function(a){this.of=a};Q(google[J].A[F],"setAutoComplete",google[J].A[F].pj);
google[J].A[F].kj=function(a,c,d){this.Z={};this.Z.yg=a;this.Z.Ni=c||"q";this.Z.Mi=d||!1};Q(google[J].A[F],"enableSearchboxOnly",google[J].A[F].kj);
google[J].B=function(a,c,d){this.v=d;this.ld=this.md=!1;this.h=a;this.D=f;this.Ug=S(c,google[J].b[F].jh,[this]);this.Xg=S(c,google[J].b[F].nd,[this,google[J].B.Zc]);this.Wg=S(c,google[J].b[F].nd,[this,google[J].B.Yc]);this.Vg=S(c,google[J].b[F].nd,[this,google[J].B.ke]);this.Tg=S(c,google[J].b[F].ih,[this]);this.Sg=S(c,google[J].b[F].hh,[this]);this.h.pb(c,google[J].b[F].ca,[this]);this.h.U(c.Ob);this.h.Wb(c.Ya);ra(this,f);this.Q=this.lb=this.Ra=this.Sc=this.Fb=this.nc=f;this.Lb=!0};
google[J].B.Oc=0;google[J].B.Zc=1;google[J].B.Yc=2;google[J].B.ke=3;google[J].B[F].Nc=function(a){var c="gsc-results-selector ";c+=a==google[J].B.Oc?this.v.fa==google[J].b.Xa?"gsc-one-result-active":this.h.Aa==google[J].a.ga?"gsc-more-results-active":"gsc-all-results-active":a==google[J].B.Zc?"gsc-one-result-active":a==google[J].B.Yc?"gsc-more-results-active":"gsc-all-results-active";r(this.Sc,c)};
google[J].b=function(a){if(!google[L].KeyVerified)if(google[J].b.oe())google[L].KeyVerified=!0;else return;this.le=this.Ob=google[J].a.ga;this.T=google[J].b.Oa;ra(this,f);this.oc=f;ga(this,f);this.pc=google[J].b.qc;this.Jg=S(this,google[J].b[F].Zg,[f]);this.Kg=S(this,google[J].b[F].$g,[f]);this.mb=this.Gb=this.fd=this.ic=f;this.Bb=this.Lg=!1;this.Ya=google[J].a.Mb;this.Pc=R.copy;this.e=[];this.Ej=[];var c;if(a)for(var d=0;d<a[E];d++)c=new google[J].B(a[d],this,!1),this.e[sa](c)};
P("google.search.SearchControl",google[J].b);google[J].b[F].Xc=!1;google[J].b.pe=R["no-results"];Q(google[J].b,"NO_RESULTS_DEFAULT_STRING",google[J].b.pe);google[J].b.dg=350;Q(google[J].b,"TIMEOUT_SHORT",google[J].b.dg);google[J].b.qc=500;Q(google[J].b,"TIMEOUT_MEDIUM",google[J].b.qc);google[J].b.cg=700;Q(google[J].b,"TIMEOUT_LONG",google[J].b.cg);google[J].b.Xf=1;Q(google[J].b,"EXPAND_MODE_CLOSED",google[J].b.Xf);google[J].b.fb=2;Q(google[J].b,"EXPAND_MODE_OPEN",google[J].b.fb);google[J].b.Xa=3;
Q(google[J].b,"EXPAND_MODE_PARTIAL",google[J].b.Xa);google[J].b.Oa=1;Q(google[J].b,"DRAW_MODE_LINEAR",google[J].b.Oa);google[J].b.za=2;Q(google[J].b,"DRAW_MODE_TABBED",google[J].b.za);google[J].b.bg="save";Q(google[J].b,"KEEP_LABEL_SAVE",google[J].b.bg);google[J].b.ag="keep";Q(google[J].b,"KEEP_LABEL_KEEP",google[J].b.ag);google[J].b.$f="include";Q(google[J].b,"KEEP_LABEL_INCLUDE",google[J].b.$f);google[J].b.Zf="copy";Q(google[J].b,"KEEP_LABEL_COPY",google[J].b.Zf);google[J].b.Yf="blank";
Q(google[J].b,"KEEP_LABEL_BLANK",google[J].b.Yf);var Rb=google[L][ab].BUBBLEGUM,Sb=google[L][ab].GREENSKY,Tb=google[L][ab].ESPRESSO,Ub=google[L][ab].SHINY,Vb=google[L][ab].MINIMALIST;google[J].b.$a={};google[J].b.$a[Rb]={colorBackground:"#FDE5FF",colorTitleLink:"#0568CD",colorText:"#000",colorDomainLink:"#CC7A9F",fontFamily:"Arial"};
google[J].b.$a[Sb]={colorBackground:"#EEFFE5",colorBorder:"#A9DA92",colorTitleLink:"#06C",colorText:"#454545",colorDomainLink:"#8D5FA7",fontFamily:"Trebuchet MS",fontSizeTitle:"14",fontSizeDescription:"14"};google[J].b.$a[Tb]={colorBackground:"#F2F0E6",colorTitleLink:"#950000",colorText:"#333",colorDomainLink:"#A25B08",fontFamily:"Georgia",fontSizeTitle:"14",fontSizeDescription:"14",fontSizeDomainLink:"12"};
google[J].b.$a[Ub]={colorBackground:"#F0F0F6",colorBorder:"#CCC",colorTitleLink:"#06C",colorDomainLink:"#008000",fontFamily:"Verdana"};google[J].b.$a[Vb]={colorBackground:"#EEE",colorBorder:"#CCC",colorTitleLink:"#000",colorText:"#444",colorDomainLink:"#333",fontFamily:"Arial"};google[J].b.Qc="gsc-loading-id";try{google[J].b.appPath=k[Ua][$a]}catch(Xb){google[J].b.appPath=f}
google[J].b.oe=function(){var a;a=k[Ua].host[gb]()[Sa](".");if(a[E]<2)a=!1;else{var c=a.pop(),d=a.pop();(d=="igoogle"||d=="gmodules"||d=="googlesyndication")&&c=="com"?a=!0:(c[E]==2&&a[E]>0&&Fb[d]&&Fb[d][c]==1&&(d=a.pop()),a=d=="google")}if(a)return!0;google[L].KeyVerified=!0;google[L].LoadFailure=!1;return!0};Q(google[J].b,"keyCheck",google[J].b.oe);google[J].b[F].ri=function(){var a=this;return function(){if(a.Xc)a.ie(),a.Xc=!1}};
google[J].b[F].Sb=function(a,c){google.load("ads.search","2",{callback:this.ri()});this.Na=!0;this.Za=a;if(c){if(c.includeVerticalAds!=b)this.pa=c.includeVerticalAds;if(c.includeSideAds!=b)this.pa=c.includeSideAds;if(c.iframes!=b)this.Db=c.iframes;if(c.useNarrowTopAd!=b&&this.Db)this.Lj=c.useNarrowTopAd;if(c.channel)this.fe=c.channel;if(c.clientIP)this.ge=c.clientIP;if(c.safe)this.Wc=c.safe;if(c.userAgent)this.he=c.userAgent;var d=c.adtest||c.debug;if(d)this.Tc=d;if(c.numTopAds!=b)this.qa=c.numTopAds,
this.qa=n.max(0,n.min(4,this.qa));if(c.numSideAds!=b)this.ha=c.numSideAds,this.pa=(this.ha=n.max(0,n.min(8,this.ha)))?!0:!1;this.je=c.enableSearchCompleteCallback?!0:!1}};Q(google[J].b[F],"enableAds",google[J].b[F].Sb);google[J].b[F].gb=function(a,c){c||(c=new google[J].H);a.Da=f;this.e[sa](new google[J].B(a,this,c));if(this.lc(a))this.Ig=!0;a.rc="gsc"};Q(google[J].b[F],"addSearcher",google[J].b[F].gb);
google[J].b[F].Zd=function(a){this.e[a].v[N]?(this.e[a].Lb=!1,ra(this.e[a],this.e[a].v[N]),Z(this.e[a][N],"gsc-resultsRoot"),$(this.e[a][N],"gsc-resultsbox-visible"),Z(this.e[a][N],"gsc-resultsbox-invisible")):ra(this.e[a],V("gsc-resultsRoot"));this.e[a].h.Eb&&Z(this.e[a][N],"gsc-resultsRoot-"+this.e[a].h.Eb);if(this.T==google[J].b.za)this.k[a].I=this.e[a][N];var c=vb(f,f,"gsc-resultsHeader"),d=wb(c,0);this.e[a].ab=W(d,"gsc-twiddleRegionCell");d=W(d,"gsc-configLabelCell");this.e[a].nc=U("","gsc-twiddle");
T(this.e[a].ab,this.e[a].nc);var e=tb(this.e[a].h.bh(),"gsc-title");T(this.e[a].nc,e);this.e[a].Fb=U("","gsc-stats");T(this.e[a].ab,this.e[a].Fb);var e=U(),g=U(R.blank,"gsc-result-selector gsc-one-result"),i=U(R.blank,"gsc-result-selector gsc-more-results"),l=U(R.blank,"gsc-result-selector gsc-all-results");ja(g,R["show-one-result"]);ja(i,R["show-more-results"]);ja(l,R["show-all-results"]);T(e,g);T(e,i);T(e,l);na(g,this.e[a].Xg);na(i,this.e[a].Wg);na(l,this.e[a].Vg);this.e[a].Sc=e;this.e[a].Nc(google[J].B.Oc);
T(this.e[a].ab,this.e[a].Sc);na(this.e[a].nc,this.e[a].Ug);if(this.e[a].h.na)this.e[a].$=ub("","gsc-configLabel"),o(this.e[a].$,R.blank),Z(this.e[a].$,"gsc-twiddle-closed"),T(d,this.e[a].$),na(this.e[a].$,this.e[a].Tg),ja(this.e[a].$,R.settings),this.e[a].Ra=V("gsc-config"),Z(this.e[a].Ra,this.e[a].h.ib),this.e[a].lb=Ab("gsc-config"),Z(this.e[a].lb,this.e[a].h.ib),this.e[a].lb.onsubmit=this.e[a].Sg,T(this.e[a].Ra,this.e[a].lb),oa(this.e[a].Ra[I],"none");this.e[a].Q=V("gsc-results");d=this.e[a].h.jc();
Z(this.e[a].Q,d);this.e[a].Q.onmousedown=pb(this,google[J].b[F].ah);this.e[a].v[N]==f&&T(this.Ma,this.e[a][N]);T(this.e[a][N],c);this.e[a].Ra&&T(this.e[a][N],this.e[a].Ra);T(this.e[a][N],this.e[a].Q)};google[J].b.eg={};google[J].b.Yh=0;google[J].b.Xh=/^\/\/www\.google\.com\/url\?/;google[J].b.Zh=function(){return new Image};
google[J].b[F].ah=function(a){a=a||k[hb];for(a=a.target||a.srcElement;a;){if(a[$a]&&a.getAttribute("data-cturl"))break;a=a[cb]}if(a&&(a=a.getAttribute("data-cturl"))&&google[J].b.Xh.test(a)){var c=google[J].b.Zh(),d=google[J].b.Yh++;google[J].b.eg[d]=c;c.onload=c.onerror=c.onabort=function(){delete google[J].b.eg[d]};c.src=a}return!0};
google[J].b[F].$d=function(a){var c=this.e[a],d={},e=c.h.fh();d.aa=tb(e);d.I=f;d.Rc=c.h;d.z=c.h.z;na(d.aa,S(this,this.gh,[a]));this.k[a]=d;T(this.ea,d.aa);a="gs-spacer";lb("opera")&&(a+=" gs-spacer-opera");a=ub(" ",a);T(this.ea,a);c.v.df(google[J].b.fb)};
google[J].b[F].Tb=function(a,c){var d=f,e=f;c?c.T?(this.T=c.T,d=c[t],e=c.Ye,this.Z=c.Z):this.T=google[J].b.Oa:this.T=google[J].b.Oa;ra(this,V(this.Z?"gsc-control-searchbox-only":"gsc-control"));d!=f?(ga(this,d),this[t].onkeyup=this.Jg,this[t].onpaste=this.Kg):(e==f&&(e=this[N]),d=new google[J].L(!0,e),d.$e(this,this[va]),d.Ze(this,this.kd),ga(this,d[t]),this.Cb&&d.eh());if(!this.Z){this.Ma=V("gsc-resultsbox-invisible");if(this.T==google[J].b.za){this.ea=V("gsc-tabsAreaInvisible");T(this[N],this.ea);
this.k=[];for(d=this.t=0;d<this.e[E];d++)this.$d(d)}this.ba=this[N];if(this.Na)this.ba=V("gsc-wrapper"),this.W=V("gsc-adBlockInvisible"),this.R=V("gsc-adBlockInvisible"),T(this.ba,this.W),T(this[N],this.R),T(this[N],this.ba);T(this.ba,this.Ma);for(d=0;d<this.e[E];d++)this.Zd(d),this.T==google[J].b.za&&(Z(this.k[d].aa,"gsc-tabHeader"),Z(this.k[d].I,"gsc-tabData"),d==this.t?(Z(this.k[d].aa,"gsc-tabhActive"),Z(this.k[d].I,"gsc-tabdActive")):(Z(this.k[d].aa,"gsc-tabhInactive"),Z(this.k[d].I,"gsc-tabdInactive")))}a&&
typeof a=="string"&&(a=m[x](a));if(a&&(rb(a,this[N]),(d=this.dh())&&d<300))this.Lg=!0,Z(this[N],"gsc-narrow")};Q(google[J].b[F],"draw",google[J].b[F].Tb);google[J].b[F].zj=function(a){switch(a){case google[J].b.dg:case google[J].b.qc:case google[J].b.cg:this.pc=a;break;default:this.pc=google[J].b.qc}};Q(google[J].b[F],"setTimeoutInterval",google[J].b[F].zj);
google[J].b[F].tj=function(a,c,d){if(d)switch(d){case google[J].b.bg:case google[J].b.ag:case google[J].b.$f:case google[J].b.Zf:case google[J].b.Yf:this.Pc=R[d];break;default:this.Pc=d}this.ic=pb(a,c)};Q(google[J].b[F],"setOnKeepCallback",google[J].b[F].tj);O=google[J].b[F];O.lc=function(a){var c=a.z;if(this.Cb){if(c=="web"&&a.F!=google[J].g.da)return!1;return!0}else return c=="blog"||c=="image"?!0:!1};
O.gh=function(a){if(this.t!=a)if($(this.k[this.t].aa,"gsc-tabhActive"),$(this.k[this.t].I,"gsc-tabdActive"),Z(this.k[this.t].aa,"gsc-tabhInactive"),Z(this.k[this.t].I,"gsc-tabdInactive"),this.t=a,a=this.k[this.t].Rc,Z(this.k[this.t].aa,"gsc-tabhActive"),$(this.k[this.t].aa,"gsc-tabhInactive"),this.Na&&(this.lc(a)?this.Nb():this.Bd()),this.Vc&&a.qf==this.Vc)Z(this.k[this.t].I,"gsc-tabdActive"),$(this.k[this.t].I,"gsc-tabdInactive");else{var c=m[x](google[J].b.Qc);if(!c)c=m[A]("div"),c.id=google[J].b.Qc,
c[s](m.createTextNode("Loading...")),this.k[this.t].I[cb].insertBefore(c,this.k[this.t].I);this.Uc(a,this.k[this.t].I,this.Vc)}};O.Nb=function(){this.Na&&(r(this.W,"gsc-adBlockInvisible"),r(this.R,"gsc-adBlockInvisible"),this.pa&&$(this.ba,"gsc-thinWrapper"))};O.Bd=function(){this.Na&&(r(this.W,this.rb&&this.rb>0?"gsc-adBlock":"gsc-adBlockInvisible"),this.qb&&this.qb>0?(r(this.R,"gsc-adBlockVertical"),Z(this.ba,"gsc-thinWrapper")):(r(this.R,"gsc-adBlockInvisible"),$(this.ba,"gsc-thinWrapper")))};
O.submit=function(){if(this[t][y][E])if(this.Z){var a=this.Z.yg+(this.Z.yg[Ca]("?")>=0?"&":"?")+h(this.Z.Ni)+"="+h(this[t][y]);this.Z.Mi?k.open(a):k.location=a}else this[M]();else this.kd();return!1};Q(google[J].b[F],"submit",google[J].b[F][va]);google[J].b[F].hc=function(){this.ea&&!this.ph&&(!this.Cb||this.e[E]>1)&&r(this.ea,"gsc-tabsArea")};
google[J].b[F].jg=function(a){var c=this;return function(d,e){if(e)a?c.rb=1:c.qb=1,c.rb>0&&(c.pa&&c.qb>1||!c.pa)?(k[ua](c.Li),c.Bd()):c.Li=k[Qa](function(){c.Bd()},200)}};
pa(google[J].b[F],function(a,c){var d;if(a){d=a;if(this[t].onfocus)this[t].onfocus();q(this[t],d)}else d=this[t][y];if(d[E]){this.Bb=!1;r(this.Ma,"gsc-resultsbox-visible");this.hc();this.Pb=google[L].createGuidArg_();var e=this.Na;e&&this.Ig&&this.T==google[J].b.Oa&&(e=!1);var g=this.Og(),i=this.Ng();g==b&&!this.Za&&!this.Db&&(e=!1);if(e){this.Qg();e="w"+this.qa;this.pa&&(e=e+"n"+this.ha);var l;if(this.Db){this.Ma[I].visibility="hidden";this.Nb();o(this.W,"");o(this.R,"");this.ia={};this.ia.pubId=
this.Za||"google-coop";this.ia.gcsc=!0;g?this.ia.cx=g:i&&(this.ia.cref=i);this.ia.hl=google[J][db]?h(google[J][db]):f;this.ia.adtest=this.Tc?"on":f;this.ia.adsafe=this.Wc||f;this.ia.query=d;if((i=google[J].a.Mg())&&i in google[J].b.$a){var i=google[J].b.$a[i],p;for(p in i)this.ia[p]=i[p]}google&&google.ads&&google.ads[J]&&google.ads[J].Ads?this.ie():this.Xc=!0}else l="http://www.google.com/"+(g?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+h(d)+"&hl="+h(google[J][db])+"&ad="+h(e)+"&js=uds&"+
this.Pb;g&&(l+="&cx="+g);this.Za&&(l+="&client="+h(this.Za));this.fe&&(l+="&channel="+h(this.fe));this.Tc&&(l+="&adtest=on");this.ge&&(l+="&ip="+h(this.ge));this.Wc&&(l+="&adsafe="+h(this.Wc));this.he&&(l+="&useragent="+h(this.he));if(!this.Db){var u=this;k.google_afs_request_done=function(a){u.Pg(a)};ob(l)}}this.Vc=d;if(this.T==google[J].b.za)this.Uc(this.k[this.t].Rc,this.k[this.t].I,d,c);else for(g=0;g<this.e[E];g++)this.Uc(this.e[g].h,this.e[g][N],d,c)}});Q(google[J].b[F],"execute",google[J].b[F][M]);
O=google[J].b[F];
O.ie=function(){this.qb=this.rb=0;if(this.qa&&this.qa>0)this.kg={container:this.W,number:this.qa,callback:this.jg(!0),lines:2},r(this.W,"gsc-adBlockNoHeight"),qa(this.W[I],"0px");if(this.pa&&this.ha&&this.ha>0)this.ni={container:this.R,number:this.ha,callback:this.jg(!1)},r(this.R,"gsc-adBlockVertical"),Z(this.R,"gsc-adBlockNoHeight"),Z(this.ba,"gsc-thinWrapper"),qa(this.R[I],"0px");this.qa&&this.qa>0&&(this.pa&&this.ha&&this.ha>0?new google.ads[J].Ads(this.ia,this.kg,this.ni):new google.ads[J].Ads(this.ia,this.kg))};
O.Uc=function(a,c,d,e){!a.Lb&&this.T!=google[J].b.za&&($(c,"gsc-resultsbox-invisible"),Z(c,"gsc-resultsbox-visible"));this.fd&&this.fd(this,a,d);if(a.Da)a.Da=f;a.Pb=this.Pb;e?a.Wf(e):a[M](d)};O.Og=function(){for(var a=0;a<this.e[E];a++){var c=this.e[a].h;if(c.z=="web"&&c.F!=google[J].g.da&&c.F==google[J].g.Qb)return c.l}return f};O.Ng=function(){for(var a=0;a<this.e[E];a++){var c=this.e[a].h;if(c.z=="web"&&c.F!=google[J].g.da&&c.F==google[J].g.Kj)return c.l}return f};
O.Pg=function(a){k.google_afs_request_done=f;if(this.W)if(o(this.W,""),o(this.R,""),this.rb=this.qb=0,!a||a[E]<1)this.Nb();else{if(!this.ea)for(var c=0;c<this.e[E];c++){var d=this.e[c].h;if(this.lc(d)){this.Nb();return}}r(this.W,"gsc-adBlock");var d=!1,e=m[A]("h2"),c="";this.Tc&&(c="*DEBUG* ");c+=R["ads-by-google"];o(e,c);T(this.W,e);for(var g=a[E],c=0;c<g;c++){var i=a[c];if(i[Ha]=="text/wide"){this.rb++;var l=V("gsc-ad"),p=X(i.url,i.line1,google[J].a.Mb);T(l,p);p=m[A]("cite");o(p,i.visible_url);
T(l,p);p=ub();o(p,i.line2);T(l,p);T(this.W,l)}else this.pa&&(this.qb++,d||(d=!0,Z(this.ba,"gsc-thinWrapper"),T(this.R,e[Ga](!0)),r(this.R,"gsc-adBlockVertical")),l=V("gsc-ad"),p=X(i.url,i.line1,google[J].a.Mb),T(l,p),p=ub(),o(p,i.line2+"<br/>"+i.line3),T(l,p),p=m[A]("cite"),o(p,i.visible_url),T(l,p),T(this.R,l))}this.pa&&!d&&$(this.ba,"gsc-thinWrapper");if(this.ea)d=this.k[this.t].Rc,this.lc(d)&&this.Nb();this.Gb&&this.je&&this.Gb(this,"ads")}};
O.Zg=function(){var a=this[t][y];if(a&&a!="")this.mb&&k[ua](this.mb),this.mb=k[Qa](S(this,google[J].b[F][M],[f]),this.pc)};O.$g=function(){this.mb&&k[ua](this.mb);this.mb=k[Qa](S(this,google[J].b[F][M],[f]),this.pc)};O.Qg=function(){var a,c;switch(this.le){case google[J].a.kb:a=3;c=5;break;case google[J].a.Ca:a=2;c=4;break;default:a=1,c=2}if(this.qa==b)this.qa=a;if(this.ha==b)this.ha=c};
O.U=function(a){if(a>0&&a<=8)this.Ob=a;else switch(a){case google[J].a.Ca:case google[J].a.kb:this.Ob=google[J].a.Ca;break;default:case google[J].a.ga:this.Ob=google[J].a.ga}for(var c=0;c<this.e[E];c++)this.e[c].h.U(a);this.le=a};Q(google[J].b[F],"setResultSetSize",google[J].b[F].U);google[J].b[F].Wb=function(a){this.Ya=a;for(var c=0;c<this.e[E];c++)this.e[c].h.Wb(a)};Q(google[J].b[F],"setLinkTarget",google[J].b[F].Wb);google[J].b[F].Rb=function(a){for(var c=0;c<this.e[E];c++)this.e[c].v.Rb(a)};
Q(google[J].b[F],"setNoResultsString",google[J].b[F].Rb);O=google[J].b[F];O.jh=function(a){a.md?this.Wa(a,!1):this.Wa(a,!0)};O.Wa=function(a,c,d){c?($(a.ab,"gsc-twiddle-closed"),Z(a.ab,"gsc-twiddle-opened"),a.md=!0,oa(a.Q[I],"block")):($(a.ab,"gsc-twiddle-opened"),Z(a.ab,"gsc-twiddle-closed"),a.md=!1,oa(a.Q[I],"none"),o(a.Fb,d?"(0)":"("+a.h.results[E]+")"))};O.hh=function(a){this.Jb(a,!1,!0);return!1};O.ih=function(a){a.h.ob&&(a.ld?this.Jb(a,!1,!0):this.Jb(a,!0,!0))};
O.Jb=function(a,c,d){if(c){if(a.$&&a.h.na)Z(a.$,"gsc-twiddle-opened"),$(a.$,"gsc-twiddle-closed"),o(a.$,R[Wa]),a.ld=!0,oa(a.Ra[I],"block"),a.h.na(a.lb,!0)}else if(a.$&&a.h.na)$(a.$,"gsc-twiddle-opened"),Z(a.$,"gsc-twiddle-closed"),o(a.$,R.blank),a.ld=!1,a.h.na(a.lb,!1),oa(a.Ra[I],"none"),d&&this[M]()};O.Hg=function(a){this.ic&&this.ic(a)};O.ej=function(){this.Bb=!0};Q(google[J].b[F],"cancelSearch",google[J].b[F].ej);
google[J].b[F].kd=function(){q(this[t],"");if(this[t].onblur)this[t].onblur();r(this.Ma,"gsc-resultsbox-invisible");this.ea&&r(this.ea,"gsc-tabsAreaInvisible");this.W&&r(this.W,"gsc-adBlockInvisible");this.R&&(r(this.R,"gsc-adBlockInvisible"),$(this.ba,"gsc-thinWrapper"));for(var a=0;a<this.e[E];a++){this.e[a].Lb||($(this.e[a][N],"gsc-resultsbox-visible"),Z(this.e[a][N],"gsc-resultsbox-invisible"));var c=this.e[a];qb(c.Q);c.D=f;this.Wa(c,!1,!0);this.Jb(c,!1,!1)}};
Q(google[J].b[F],"clearAllResults",google[J].b[F].kd);
google[J].b[F].ca=function(a){if(this.Db&&a==this.e[this.t])this.Ma[I].visibility="visible";this.k&&this.k[this.t]&&this.k[this.t].I&&(Z(this.k[this.t].I,"gsc-tabdActive"),$(this.k[this.t].I,"gsc-tabdInactive"));var c=m[x](google[J].b.Qc);c&&c[cb][Ya](c);var d,e=!1,g;if(!this.Bb){qb(a.Q);a.D=f;this.Wa(a,!1,!0);this.Jb(a,!1,!1);a.Nc(google[J].B.Oc);if(c=a.h.spelling)if(c.html||a.h.de(c),c.html){var i=c.html[Ga](!0),l=i[Ka]("a");l&&l[E]>0&&na(l[0],S(this,google[J].b[F][M],[c.correctedQuery]));g=V(a.h.jc());
Z(g,"gsc-result");T(g,i);T(a.Q,g)}var l=a.h.context,p=this.ea&&l;if(this.Cb&&!this.Dg){if(p){g=l[Ma];for(c=0;c<this.k[E];c++)if(i=this.k[c],i.z==a.h.z){var u=a.h;g&&!a.h.eb&&rb(i.aa,sb(g));break}this.Dg=!0}this.hc()}if((d=a.h.promotions)&&d[E]>0)for(c=0;c<d[E];c++)i=d[c],i.html||a.h.ce(i),i.html&&(g=V(a.h.jc()),Z(g,"gsc-result"),i=i.html[Ga](!0),T(g,i),T(a.Q,g));var z=a.h.results;a.h.Hb&&a.h.completionStatus>=400?(z=[],z[sa](a.h.Fg())):z[E]==0&&a.v.Ib&&a.h.completionStatus==200&&(z=[],z[sa](a.h.Gg(a.v.Ib)));
for(c=0;c<z[E];c++)if(d=z[c],d.html||a.h.K(d),d.html){e=!0;g=V(a.h.jc());Z(g,"gsc-result");a.h.Eb&&Z(g,"gsc-result-"+a.h.Eb);i=d.html[Ga](!0);if(d.GsearchResultClass==google[J].c.J){if(a.v.V&&(a.v.V[v]!=a.h.V[v]||a.v.V[eb]!=a.h.V[eb]))for(var G=i[Ka]("img"),Y=0;Y<G[E];Y++)google[J].a.hb(d.tbWidth,d.tbHeight,a.v.V,G[Y],!0)}else if(d.GsearchResultClass==google[J].r.J&&a.v.kc){G=i[Ka]("img");for(Y=0;Y<G[E];Y++)google[J].a.hb(d.tbWidth,d.tbHeight,a.v.kc,G[Y])}T(g,i);if(this.ic)i=this.Pc,G=U("","gsc-keeper"),
o(G,i),T(g,G),na(G,S(this,google[J].b[F].Hg,[d,a]));if(c>=a.h.Yd){if(!a.D)a.D=V("gsc-expansionArea"),T(a.Q,a.D),a.v.fa==google[J].b.Xa&&oa(a.D[I],"none");T(a.D,g)}else T(a.Q,g)}if(!a.D&&a.h[H])a.D=V("gsc-expansionArea"),T(a.Q,a.D);a.D&&a.h.w&&a.h.gwsUrl&&a.h[H]&&(c=V("gsc-cursor-box"),g=this.Eg(a),c[s](g),T(a.D,c));e?(o(a.Fb,"("+a.h.results[E]+")"),a.v.fa==google[J].b.Xa||a.v.fa==google[J].b.fb?this.Wa(a,!0):this.Wa(a,!1),(c=a.h.ee())&&T(a.Q,c)):(o(a.Fb,"(0)"),o(a.Q,""),this.Wa(a,!1));a.v.fa=a.v.ae;
this.Gb&&this.Gb(this,a.h);if(this.Cb&&p&&!this.be&&l.facets){a=this[t][y];e=l.facets;for(c=0;c<e[E];c++){l=e[c];p=new google[J].g;if(u){u.l&&p.Ba(u.l,l.label);if(u.C)p.C=u.C;if(u.ma)p.ma=u.ma}p.Kb(l.anchor);this.gb(p);p.U(u.Aa);this.T!=google[J].b.za&&p[M](a)}this.e[E]>1&&!this.be&&r(this.ea,"gsc-tabsArea");for(c=0;c<this.e[E];c++)this.k[c]||(this.$d(c),this.Zd(c),Z(this.k[c].aa,"gsc-tabHeader"),Z(this.k[c].I,"gsc-tabData"),Z(this.k[c].aa,"gsc-tabhInactive"),Z(this.k[c].I,"gsc-tabdInactive"));this.be=
!0}}};Q(google[J].b[F],"onSearchComplete",google[J].b[F].ca);google[J].b[F].Eg=function(a){for(var c=V("gsc-cursor"),d=a.h[H],e=0;e<d.pages[E];e++){var g="gsc-cursor-page";e==d.currentPageIndex&&(g+=" gsc-cursor-current-page");g=U(d.pages[e].label,g);na(g,S(this,google[J].b[F].Mh,[a,e]));c[s](g)}return c};
google[J].b.fg={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
google[J].b.gg=function(a,c){if(lb("safari")||lb("konqueror"))alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var d=!0;c&&(d=c);if(d)for(d=0;d<a.childNodes[E];d++)google[J].b.gg(a.childNodes[d],!0);if(a[xa]==1){var e,g,i=!1,d=!1;k[Va]?(e=k[Va](a,f),i=g=!0):a[Za]&&(e=a[Za],g=!1,i=!0);if(i){for(var l in e)if(google[J].b.fg[l]){var i=google[J].b.fg[l],p=e[l];l=="display"&&p=="none"&&(o(a,""),d=!0);e[l]!=""&&(g?a[I].setProperty(i,p):a[I][C](i,p))}if(d&&!g)a.outerHTML=
'<div style="display:none"/>'}}}};Q(google[J].b,"inlineCurrentStyle",google[J].b.gg);google[J].b[F].dh=function(a){var a=a?a:this[N],c=f;k[Va]?c=k[Va](a,f):a[Za]?c=a[Za]:m.defaultView[Va]&&(c=m.defaultView[Va](a,f));return c?ca(c[v],10):300};google[J].b[F].pb=function(a,c){this.Gb=pb(a,c)};Q(google[J].b[F],"setSearchCompleteCallback",google[J].b[F].pb);google[J].b[F].xj=function(a,c){this.fd=pb(a,c)};Q(google[J].b[F],"setSearchStartingCallback",google[J].b[F].xj);
google[J].b[F].nd=function(a,c){a.Nc(c);var d=!1;switch(c){default:case google[J].B.Zc:a.D&&oa(a.D[I],"none");break;case google[J].B.Yc:a.D&&oa(a.D[I],"block");a.h.Aa!=google[J].a.ga&&(d=!0);a.h.U(google[J].a.ga);break;case google[J].B.ke:a.D&&oa(a.D[I],"block"),a.h.Aa!=google[J].a.Ca&&(d=!0),a.h.U(google[J].a.Ca)}if(d&&(d=this[t][y],d[E]))this.Bb=!1,r(this.Ma,"gsc-resultsbox-visible"),this.hc(),a.Lb||($(a[N],"gsc-resultsbox-invisible"),Z(a[N],"gsc-resultsbox-visible")),a.v.fa=google[J].b.fb,a.h[M](d)};
google[J].b[F].Mh=function(a,c){this.Bb=!1;r(this.Ma,"gsc-resultsbox-visible");this.hc();a.Lb||($(a[N],"gsc-resultsbox-invisible"),Z(a[N],"gsc-resultsbox-visible"));a.v.fa=google[J].b.fb;a.h.Ef(c)};
google[J].L=function(a,c,d){var e=Ab("gsc-search-box");e.acceptCharset="utf-8";var g=f,i=R["search-uc"],l=R[J];if(d){if(d.buttonText)l=i=d.buttonText;if(d.clickableBrandingUrl)g="http://www.google.com",typeof d.clickableBrandingUrl=="string"&&d.clickableBrandingUrl[Da](/^http:\/\/[a-z]*\.google\.com/)&&(g=d.clickableBrandingUrl),g=zb(g,f,"_BLANK"),r(g,"gsc-branding-clickable")}this.oc=Bb(i,"gsc-search-button");ja(this.oc,l);a?(d="gsc-branding-img",this.Xd=U(R.blank,"gsc-clear-button"),ja(this.Xd,
R["clear-results"])):d="gsc-branding-img-noclear";ga(this,Cb(f,"gsc-input",f));this[t].name="search";ja(this[t],l);l=vb(f,f,"gsc-search-box");T(e,l);l=wb(l,0);this.Bg=W(l,"gsc-input");i=W(l,"gsc-search-button");a&&(a=W(l,"gsc-clear-button"),T(a,this.Xd));T(this.Bg,this[t]);T(i,this.oc);a=vb(f,f,"gsc-branding");T(e,a);l=wb(a,0);this.userDefinedCell=W(l,"gsc-branding-user-defined");var a=W(l,"gsc-branding-text"),l=W(l,d),i=U(R["powered-by"],"gsc-branding-text"),p=google[L][Ia]+"/css/small-logo.png";
lb("msie")?(d=V(d),d[I].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+p+'")',ha(d[I],"51px"),qa(d[I],"15px")):d=yb(p,f,f,d);T(a,i);g?(T(g,d),T(l,g)):T(l,d);this.zg=e;qb(c);T(c,this.zg)};P("google.search.SearchForm",google[J].L);google[J].L.wg=function(){return"#FFFFFF url(//www.google.com/cse/intl/"+google[J][db]+"/images/google_custom_search_watermark.gif) left no-repeat"};
google[J].L[F].$e=function(a,c){this.Cg=S(this,this.Oi,[this]);this.Mc=S(a,c,[this]);this.zg.onsubmit=this.Cg;na(this.oc,this.Cg)};Q(google[J].L[F],"setOnSubmitCallback",google[J].L[F].$e);google[J].L[F].Ze=function(a,c){na(this.Xd,S(a,c,[this]))};Q(google[J].L[F],"setOnClearCallback",google[J].L[F].Ze);google[J].L[F].Oi=function(){var a=this.Bg[Aa],c=this[t][y];this.Mc&&this.Mc();if(lb("msie")){var d=this,e;e=c[E]*8>=a?a-6:"99%";k[Qa](function(){ha(d[t][I],e)},1)}return!1};
pa(google[J].L[F],function(a){a&&q(this[t],a);this.Mc&&this.Mc()});Q(google[J].L[F],"execute",google[J].L[F][M]);google[J].L[F].eh=function(){var a=this[t],c=function(){if(a[y]=="")a[I].background=google[J].L.wg()};a.onblur=c;a.onfocus=function(){a[I].background="#FFFFFF"};c()};google[J].xg=function(a,c,d,e){this.ua=d[Ga](!0);this.ua.id="gsci-content"+e;d[cb].insertBefore(this.ua,d);d=new google[J].A;d.nf(c);this.Ac=new google[J].i(a);this.Ac.U(google[J].a.ga);this.Ac.Tb(this.ua,d);this.xc=!1;this.Bc=f;la(this,f);this.Va=f};O=google[J].xg[F];O.Sd=function(){oa(this.ua[I],"none");$(this.ua,"fade")};O.show=function(){oa(this.ua[I],"block");$(this.ua,"fade")};O.Pi=function(){Z(this.ua,"fade")};
O.send=function(a,c){if(!this.xc){var d=this;this.Ac.pb(this,function(){this.xc=!1;if(d.Bc)d.Bc(d),d.Bc=f});this.xc=!0;this.Ac[M](a,c)}};O.Ud=function(a){this.Bc=a};google[J].fc=function(a,c,d,e){this.Pd=this.Ab=f;for(var g=0;g<e;g++)this.tg(new google[J].xg(a,c,d,g));this.Kc={};this.xa=f};google[J].fc[F].tg=function(a){la(a,this.Ab);a.Va=f;this.Ab==f?this.Pd=a:this.Ab.Va=a;this.Ab=a};
google[J].fc[F].zi=function(a){a.Va==f?this.Ab=a[Ra]:la(a.Va,a[Ra]);a[Ra]==f?this.Pd=a.Va:a[Ra].Va=a.Va;a.Va=f;la(a,f);return a};google[J].fc[F].get=function(a,c,d){if(!a&&d)d(f);else{if(d)for(var e=this.Ab;e!=f;e=e[Ra])e.Ud(f);if(a in this.Kc)e=this.Kc[a],d&&(e.xc?e.Ud(d):d(e));else{e=this.Pd;delete this.Kc[e.Pj];if(this.xa==e)e.Sd(),this.xa=f;this.Kc[a]=e;d&&e.Ud(d);e.send(a,c)}this.zi(e);this.tg(e)}};
google[J].fc[F].show=function(a,c){if(a){this.xa!=f&&this.xa.Pi();var d=this;this.get(a,c,function(a){d.xa&&d.xa.Sd();a&&a[ta]();d.xa=a})}else this.xa&&this.xa.Sd(),this.xa=f};
google[J].G=function(a,c){this.Jd=a;c&&typeof c=="string"&&(c=m[x](c));c&&o(c,google[J].G.qi);this.O=m[x]("gsci-query");this.bi=m[x]("gsci-hidden");this.ua=m[x]("gsci-content");this.oi=m[x]("gsci-padding");this.pi=m[x]("gsci-hide");this.mg=m[x]("gsci-show");this.mi=m[x]("gsci-clear");var d=m[x]("gsci-sform");d&&q(d.cx,this.Jd);this.va=f;this.Fd=!1;this.lg()};P("google.search.CustomInstantSearchControl",google[J].G);google[J].G.Ai=300;google[J].G.ki=20;google[J].G.ji=5;
google[J].G.qi=['<form id="gsci-sform" name="f" onsubmit="return q.value != \'\'">\n  <div class="gsci-sbox">\n    <div class="gsci-sinput">\n      <input class="gsci-entry" id="gsci-query" name="q" type="text"\n        value="" autocorrect="off" autocomplete="off" maxlength="1024"\n        onfocus="this.value = this.value">\n      <div class="gsci-entry" id="gsci-grey" name="g"\n        onfocus="this.parentNode.childNodes[0].focus()">\n        <span id="gsci-hide"></span><span id="gsci-show"></span>\n      </div>\n      <a class="gsci-cross" id="gsci-clear" title="Clear search">\u00d7</a>\n    </div>\n  </div>\n  <input type="hidden" name="cx" value="">\n  <input class="gsci-sbutton" id="gsci-search" type="submit"\n    value="Search" title="Search">\n</form>\n<input id="gsci-hidden" type="text" style="display: none;">\n<div id="gsci-padding"></div>\n<div class="gsci-results" id="gsci-content" style="display: none;"></div>','<link href="'+
google[L][Ia]+'/css/gcustominstantsearch.css" type="text/css" rel="stylesheet">','<\!--[if gte IE 6]>\n  <style type="text/css"> #gsci-grey { padding-left: 0px; } </style>\n<![endif]--\>\n<\!--[if lte IE 7]>\n  <style type="text/css"> #gsci-query { top: -1px; } </style>\n<![endif]--\>'][fb]("\n");google[J].G.Vd=function(a,c){m.all?a.innerText=c:a.textContent=c};
google[J].G.Ii=function(){if(m.getElementsByClassName)return m.getElementsByClassName("gsc-completion-container")[0];else for(var a=m[Ka]("table"),c=0;c<a[E];c++){var d=a[c];if(d[Na]=="gsc-completion-container")return d}return f};O=google[J].G[F];O.La=function(a,c,d){a.addEventListener?a.addEventListener(c,this.Ld(d),!1):a.attachEvent&&a.attachEvent("on"+c,this.Ld(d))};O.Ld=function(a){var c=this;return function(){return a[bb](c,arguments)}};
O.lg=function(){this.Od=f;this.wa="";this.Gd=f;this.Hd=0;this.ec=-1;this.Ic(!0)};O.Ka=function(a){var c=this.O[y],d=c[E],e=a[Ca](c);google[J].G.Vd(this.pi,c);a&&e==0?google[J].G.Vd(this.mg,a.substring(d)):google[J].G.Vd(this.mg,"")};O.Ec=function(a){var c=0;if(a)c=a;else if(a=google[J].G.Ii())this.La(a,"mouseover",this.Ki),this.La(a,"mouseout",this.Ji),c=a.clientHeight+7;this.oi[I].marginTop=c+"px"};
O.ig=function(a,c){if(a&&a[E]>1&&a[1][E]>0){this.Ec();var d=a[1][0][0];this.va[ta](d,c);this.Ka(d);this.Gd=a[1];this.Hd=a[1][E];this.ec=-1;this.wa=d}else{this.Ec(0);k[ua](this.Od);var e=this;this.Od=k[Qa](function(){e.Od=f;e.va[ta](e.O[y]);e.Ka("")},200);this.Gd=f;this.Hd=0;this.ec=-1;this.wa=""}};O.Ic=function(a){this.O[I].background=a?google[J].L.wg():"transparent"};O.Di=function(){this.Ka(this.wa)};O.Gi=function(){this.Ka(this.wa)};
O.Ei=function(a){if((a[Fa]==google[J].d.cb||a[Fa]==google[J].d.Ga||a[Fa]==google[J].d.Dd)&&!this.Fd){this.Fd=!0;var c=this.Gd,d=this.ec,e=this.Hd;switch(a[Fa]){case google[J].d.cb:d=(d+e+1)%(e+1)-1;break;case google[J].d.Ga:d=(d+2)%(e+1)-1}this.ec=d;d>=0&&c&&c[E]>d?this.va.get(c[d][0]):this.wa?this.va.get(this.wa):this.va.get(this.O[y])}};
O.Fi=function(a){a[Fa]==google[J].d.cb||a[Fa]==google[J].d.Ga||a[Fa]==google[J].d.Dd?(this.Fd=!1,this.ec==-1?(this.wa?this.va[ta](this.wa):this.va[ta](this.O[y]),this.Ka(this.wa)):(this.va[ta](this.O[y]),this.Ka(""))):a[Fa]==google[J].d.Ff&&this.Ec(0)};O.Bi=function(){this.O[y]==""&&this.Ic(!0);var a=this;k[Qa](function(){a.Ec(0)},google[J].G.Ai)};O.Ci=function(){this.Ic(!1)};O.Hi=function(){q(this.O,"");this.va[ta]("");this.Ka("");this.lg()};O.Ki=function(){this.Ka("")};O.Ji=function(){this.Ka(this.wa)};
O.li=function(){this.La(this.O,"input",this.Di);this.La(this.O,"propertychange",this.Gi);this.La(this.O,"keydown",this.Ei);this.La(this.O,"keyup",this.Fi);this.La(this.O,"blur",this.Bi);this.La(this.O,"focus",this.Ci);this.La(this.mi,"click",this.Hi)};pa(O,function(a){this.va=new google[J].fc(this.Jd,this.bi,this.ua,google[J].G.ki);google[J].i.Kd(this.Jd,this.O,"gsci-sform",f,this.Ld(this.ig),google[J].G.ji);this.li();a&&(q(this.O,a),this.Ic(!1),this.ig(f))});Q(google[J].G[F],"execute",google[J].G[F][M]);google[J].i=function(a,c){google[J].b[K](this);this.Cb=!0;this.U(google[J].a.Ca);var d={iframes:!0};d.adtest=c&&c.adtest||f;this.Sb("",d);this.ne=!1;this.sb=new google[J].g;this.me=typeof a=="string"?a:f;if(a==b)a={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+k[Ua]},this.Rg=!0;this.sb.Ba(a);this.sb.mc=R.cse;c&&(c[google[J].a.jb]&&this.sb.Y(google[J].a.jb,c[google[J].a.jb]),c[google[J].a.nb]&&this.sb.Y(google[J].a.nb,c[google[J].a.nb]));this.gb(this.sb);this.Rb(google[J].b.pe);this.Yg=
(new Date)[D]()};P("google.search.CustomSearchControl",google[J].i);jb(google[J].i,google[J].b);
google[J].d=function(a,c,d,e,g){this.ac=a;this.kh=d;this.Ta=c[y];this.gf="";this.mf=this.hf=0;this.Zb=!1;this.lh="";this.Yb={};this.od=g;this.mh=!1;a=n[ya](n.random()*2E4)+google[J].d.rf;this.zc=google[J].d.qh+a;this.lf=google[J].d.rh+a;google[J].d.rf++;var i=this;this.tf=f;this.kf=!!e;google[J].i[this.zc]=function(a){i.vh(a);e&&e(a,i.tf)};google[J].i[this.lf]=function(a,c){i.tf=c};this.ta=c.id;if(!this.ta)this.ta="q"+this.zc,c.id=this.ta;this.tc="c"+this.zc;this.cc=!1;this.nh=function(){try{if(k[Ba]&&
k.JSON){var a=(new Date)[La](),c=a+"x";k[Ba].setItem(c,a);this.cc=k[Ba].getItem(c)===a;k[Ba].removeItem(c);this.uf();k.setInterval(this.uf,google[J].d.sh*1E3)}}catch(d){}};this.wh=function(a){for(var c=k[Ba],d=google[J].d.zd,e=[],g=0;g<c[E];g++){var i=c.key(g);i.slice(0,d[E])==d&&e[sa](i)}for(g=0;g<e[E];g++)c.removeItem(e[g]);a.Ad(google[J].d.yd,(new Date)[D]()/1E3)};this.uf=function(){var a=google[J].d,c=i.sf(a.yd);c?(new Date)[D]()/1E3-c>=a.th&&i.wh(i):i.Ad(a.yd,(new Date)[D]()/1E3)};this.xh=function(a,
c){this.cc&&k[Ba].setItem(a,c)};this.Ad=function(a,c){try{this.cc&&this.xh(a,k.JSON.stringify(c))}catch(d){}};this.uh=function(a){if(this.cc)try{var c=k[Ba].getItem(a);if(typeof c=="undefined"||c===f)return c;if(typeof c[y]=="string")return c[y];return c}catch(d){}};this.sf=function(a){if(this.cc)try{var c=this.uh(a);if(typeof c=="undefined"||c===f)return c;return k.JSON.parse(c)}catch(d){}};this.bf=function(a){return this.sf(google[J].d.zd+a)};this.oh=function(a,c){this.Ad(google[J].d.zd+a,c)}};
google[J].d.qh="GcrcGcsc";google[J].d.rh="GcrrGcsc";google[J].d.rf=0;google[J].d.xf=0;google[J].d.yc=google[J].d.xf;google[J].d.yf=2;google[J].d.Vh=10;google[J].d.Sh=10;google[J].d.Th=1;google[J].d.vd=google[J].d.yf;google[J].d.Wh=5E3;google[J].d.Pf=500;google[J].d.hi=300;google[J].d.wf=25;google[J].d.wb=google[J].d.wf;google[J].d.Uh=300;google[J].d.pf=25;google[J].d.Oh=2E3;google[J].d.Ga=40;google[J].d.cb=38;google[J].d.Dd=13;google[J].d.Ff=27;google[J].d.Qh=32;google[J].d.Nh=8;google[J].d.Ph=45;
google[J].d.ei=5;google[J].d.ci=5;google[J].d.Dc=!1;google[J].d.$b="";google[J].d.Cc=[];google[J].d.zd="sayt-";google[J].d.yd="$sayt-last-clear";google[J].d.th=900;google[J].d.sh=300;google[J].d.yb=1;google[J].d.xd=2;
google[J].d.gi=function(a,c){var d=0;if(k&&k[hb]&&k[hb][Fa])d=k[hb][Fa];else if(c&&c.which)d=c.which;if(!a.Zb&&d!=google[J].d.Ga)return!0;var e=m[x](a.ta);if(d==google[J].d.Dd)return a.jf(google[J].d.yb),!1;else if(d==google[J].d.cb)return a.Vf(d),!1;else if(d==google[J].d.Ga)return a.Vf(d),!1;else if(d==google[J].d.Ff){var g=(new Date)[D]();a.wc();q(e,a.Ta);if(g<a.hf+google[J].d.Oh)a.Zb=!1;a.hf=g}if(a.Ta==e[y]||d<=google[J].d.Ph&&d!=google[J].d.Qh&&d!=google[J].d.Nh)return!0;a.wd()};
google[J].d.fi=function(a){k[Qa](function(){a.wc()},google[J].d.hi)};google[J].d.bc=function(a,c,d){if(google[J].d.$b==d)google[J].d.Cc=a;c.oh(d,a);if(c=m[x](c.tc))for(d=0;d<google[J].d.ei;++d){var e=m[x]("google-sayt-result"+d[La]());if(d<a[E])if(e)o(e[B],a[d]);else{e=m[A]("tr");e.id="google-sayt-result"+d[La]();var g=m[A]("td");o(g,a[d]);e[s](g);c[B][s](e)}else e&&o(e[B],"")}};O=google[J].d[F];
O.di=function(){var a=m[x](this.ta);if(a)a.onkeyup=this.hg(google[J].d.gi,a.onkeyup),a.onblur=this.hg(google[J].d.fi,a.onblur)};O.jf=function(a){var c=m[x](this.ta);if(c)if(this.Ha&&a===google[J].d.xd&&q(c,this.gf),this.Ta=c[y],this.wc(),typeof this.ac=="string")if(a=m[x](this.ac),this.mh&&a.onsubmit)a.onsubmit();else a[va]();else this.ac[M]?this.ac[M]():this.ac[va]()};
O.Gc=function(a,c){for(;c&&c.id[Ca]("google-sayt-result")==0;)a==google[J].d.cb?c=c.previousSibling:a==google[J].d.Ga&&(c=c[Ja]);return c};
O.Vf=function(a){var c=m[x](google[J].i.Ed);if(c){google[J].d.ud(c,this);var d=f;a==google[J].d.cb?(d=c[cb].previousSibling,d=google[J].d[F].Gc(a,d)):a==google[J].d.Ga&&(d=c[cb][Ja],d=google[J].d[F].Gc(a,d));d&&google[J].d.Fc(d[B],this,google[J].d.yb)}else if((c=m[x](this.tc))&&a==google[J].d.cb)c=c[B].lastChild,c=google[J].d[F].Gc(a,c),google[J].d.Fc(c[B],this,google[J].d.yb);else if(c&&a==google[J].d.Ga)c=c[B][B],c=google[J].d[F].Gc(a,c),google[J].d.Fc(c[B],this,google[J].d.yb);else if(a==google[J].d.Ga)this.Zb=
!0,this.wd()};O.wc=function(){var a=m[x](this.tc);a&&a[cb][Ya](a)};
O.wd=function(){var a=this,c=m[x](a.ta);a.Ta=c[y];a.Zb&&(a.mf+google[J].d.wb>(new Date)[D]()?k[Qa](function(){a.wd()},google[J].d.wb):k[Qa](function(){var d=m[A]("script"),e=(new Date)[D]();d.src=[a.kf?google[L][Ia]+"/GcompleteSearch?q=":"//clients1.google.com/complete/search?q=",h(c[y]),"&hl=",h(google[J][db]),"&client=partner&source=gcsc&partnerid=",h(a.kh),"&callback=",h("google.search.CustomSearchControl."+a.zc),a.kf?"&rcallback="+h("google.search.CustomSearchControl."+a.lf):"","&ds=cse"][fb]("");
a.lh=c[y];m[Xa][s](d);a.Yb[c[y]]=e;a.mf=e;k[Qa](function(){a.Rf(c[y])},google[J].d.Pf)},google[J].d.yc+n[ya](n.random()*google[J].d.vd)))};
O.vh=function(a){var c=this,d=a[0];delete c.Yb[d];google[J].d.yc=google[J].d.xf;google[J].d.vd=google[J].d.yf;google[J].d.wb>google[J].d.wf&&(google[J].d.wb-=google[J].d.pf);google[J].d.Dc=!0;var e=m[x](c.ta);if(d==e[y]){c.wc();var g=a[1][E];if(!(g<1)){if(c.od&&g>c.od)g=c.od;for(var i=m[A]("tbody"),l=f,p=f,d="",u=0;u<g;++u){p=m[A]("tr");l=m[A]("td");o(l,a[1][u][0]);var z=l.innerHTML.slice(0,a[0][E]),G=l.innerHTML.slice(a[0][E]);o(l,z+"<strong>"+G+"</strong>");c.Ha&&u==0&&(d=z+G);l.onmouseover=c.Cd(l,
google[J].d.vf);if(!c.Ha)l.onmouseout=c.Cd(l,google[J].d.ud);l.onmousemove=c.Cd(l,google[J].d.Bh);na(l,function(){c.jf(google[J].d.xd)});p[s](l);i[s](p)}a=m[A]("table");a.id=c.tc;a[s](i);r(a,google[J].i.yh);a[I].top=google[J].d.Ah(e)+Ob(e,!0)+"px";a[I].left=google[J].d.zh(e)+"px";m[Xa][s](a);ha(a[I],e[Aa]+"px");if(d!="")if(google[J].d.$b==d)google[J].d.bc(google[J].d.Cc,c,d);else if(c.Ha)google[J].d.$b=d,google[J].d.Cc=[],(e=this.bf(d))?google[J].d.bc(e,c,d):c.Ha(d,google[J].d.bc,c)}}};
O.Cd=function(a,c){var d=this;return function(){c(a,d)}};O.hg=function(a,c){var d=this;return function(e){a(d,e);c&&c(e)}};
google[J].d.Fc=function(a,c,d){var e=m[x](google[J].i.Ed),g=m[x](c.ta);if(c.Ha){if(e)r(e,""),e.id=""}else e&&google[J].d.ud(e,c);e=a.textContent;if(e==b)e=a.innerText;r(a,google[J].i.Hh);a.id=google[J].i.Ed;c.Ha?d===google[J].d.yb?(c.Ta=g[y],q(g,e)):c.gf=e:(c.Ta=g[y],q(g,e));if(d===google[J].d.yb&&c.Ha&&google[J].d.$b!=e)google[J].d.$b=e,google[J].d.Cc=[],(a=c.bf(e))?google[J].d.bc(a,c,e):c.Ha(e,google[J].d.bc,c)};google[J].d.vf=function(a,c){google[J].d.Dc||google[J].d.Fc[K](this,a,c,google[J].d.xd)};
google[J].d.Bh=function(a,c){if(google[J].d.Dc)google[J].d.Dc=!1,a.onmousemove=f,google[J].d.vf[K](this,a,c)};google[J].d.ud=function(a,c){var d=m[x](c.ta);r(a,"");a.id="";q(d,c.Ta?c.Ta:"")};google[J].d.Ah=function(a){var c=0;if(a[Ta]){for(;a[Ta];)c+=a.offsetTop-a.scrollTop,a=a[Ta];c+=a.offsetTop}else a.y&&(c+=a.y);return c};google[J].d.zh=function(a){var c=0;if(a[Ta]){for(;a[Ta];)c+=a.offsetLeft-a.scrollLeft,a=a[Ta];c+=a.offsetLeft}else a.x&&(c+=a.x);return c};
google[J].d[F].Rf=function(a){var c=this;if(c.Yb[a])if((new Date)[D]()-c.Yb[a]>google[J].d.Wh)google[J].d.yc+=google[J].d.Th,google[J].d.yc*=google[J].d.Sh,google[J].d.vd+=google[J].d.Vh,google[J].d.wb<google[J].d.Uh&&(google[J].d.wb+=google[J].d.pf),delete c.Yb[a];else k[Qa](function(){c.Rf(a)},google[J].d.Pf)};google[J].i.Kd=function(a,c,d,e,g,i){if(e)i=google[J].d.ci;a=new google[J].d(d,c,a,g,i);a.Zb=!0;a.Ha=e;a.di();e&&a.nh();return a};Q(google[J].i,"attachAutoCompletion",google[J].i.Kd);
google[J].i[F].zf=function(){this.me?(google[J].i.Kd(this.me,this[t],this),this.ne=!0):this.ne=!1};Q(google[J].i[F],"enableAutoCompletion",google[J].i[F].zf);google[J].i[F].Tb=function(a,c){var d=c;d||(d=new google[J].A);d.Af(google[J].b.za);if(this.Rg&&this.e[E]==1)this.ph=!0;google[J].b[F].Tb[K](this,a,d);var e=this.Z?"gsc-control-searchbox-only":"gsc-control-cse";r(this[N],e);Z(this[N],e+"-"+google[J][db]);d.of&&this.zf()};Q(google[J].i[F],"draw",google[J].i[F].Tb);
pa(google[J].i[F],function(a,c){var d=this[N][Aa];$(this.ba,"gsc-thinWrapper");if(d<google[J].i.Dh)this.Na=!1;else if(d<google[J].i.Fh)this.Sb(this.Za,{useNarrowTopAd:!0,includeVerticalAds:!1});else{d={useNarrowTopAd:!1,includeVerticalAds:d>google[J].i.Eh};if(this.Jf)d.numTopAds=google[J].i.Gh;this.Sb(this.Za,d)}if((new Date)[D]()-this.Yg<google[J].i.Ch&&this.Na)try{var e=fa(k[Ua][$a])[w](/\+/g," "),g=fa(a)[w](/\+/g," ");this.Na=e[Ca](g)!=-1}catch(i){}google[J].b[F][M][K](this,a,c)});
Q(google[J].i[F],"execute",google[J].i[F][M]);google[J].i[F].Kb=function(a){this.sb.Kb(a)};Q(google[J].i[F],"setUserDefinedLabel",google[J].i[F].Kb);google[J].i[F].gb=function(a,c){google[J].b[F].gb[K](this,a,c);a.rc="gcsc"};Q(google[J].i[F],"addSearcher",google[J].i[F].gb);google[J].i[F].jj=function(){google[J].b[F].Sb("",{numTopAds:0,numSideAds:0});this.Za=f;this.je=!1};Q(google[J].i[F],"disableAds",google[J].i[F].jj);google[J].i[F].rj=function(){this.Jf=!0};Q(google[J].i[F],"setMoreAds",google[J].i[F].rj);
google[J].i.Qi="";Q(google[J].i,"AUTO_PUBID",google[J].i.Qi);google[J].i.Dh=250;google[J].i.Fh=500;google[J].i.Eh=800;google[J].i.Ch=500;google[J].i[F].Jf=!1;google[J].i.Gh=4;google[J].i.Ed="csc-completion-selected";google[J].i.Hh="gsc-completion-selected";google[J].i.yh="gsc-completion-container";google[J].r=function(){google[J].a[K](this);this.z="video";this.Qa="/GvideoSearch";this.Ea="http://video.google.com/videosearch";this.X=!1;this.ob=!0;this.na=pb(this,this.Fa);this.ib="gsc-videoConfig";this.p=f};P("google.search.VideoSearch",google[J].r);jb(google[J].r,google[J].a);google[J].r.J="GvideoSearch";Q(google[J].r,"RESULT_CLASS",google[J].r.J);google[J].r.n=[];google[J].r.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].r.n[i];google[J].r.n[i]=f;a.ca(c,d,e,g)};
Q(google[J].r,"RawCompletion",google[J].r.P);google[J].r[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].r.n,this):d;c=this.Pa(c==f?"google.search.VideoSearch.RawCompletion":c,d,e);this.M&&(a=a+" "+this.M);a="&q="+h(a);this.X&&(a+="&scoring=d");c+=a;this.w=a;if(e&&e!=0)this.w=this.w+"&start="+e;return c};
google[J].r[F].K=function(a){a.html&&delete a.html;var c=V(this.Ia());Z(c,"gs-result");var d=V("gs-image-box"),e=V("gs-text-box"),g=vb(),i=wb(g,0),l=W(i,"gs-image-box"),i=W(i,"gs-text-box");T(l,d);T(i,e);T(c,g);g=google[J].a.hb(a.tbWidth,a.tbHeight,this.V);g=yb(a.tbUrl,g[v],g[eb],"gs-image");l=zb(a.url,f,this.u(),"gs-image");r(l,"gs-image");T(l,g);T(d,l);d=X(a.url,a[Ma],this.u(),"gs-title");T(e,d);d=U(a[za],"gs-snippet");lb("msie")&&qa(d[I],"2.6em");T(e,d);d=U(this.zb(new Date(a.published)),"gs-publishedDate");
T(e,d);d=X("http://"+a.publisher,a.publisher,this.u(),"gs-publisher");T(e,d);a.html=c;this.Ua(a.html)};Q(google[J].r[F],"createResultHtml",google[J].r[F].K);
google[J].r.ij=function(a,c){var d=f;if(a.playUrl&&a.playUrl!=""){var d=a.playUrl,e="gsc-video-player";c&&(e=c);if(lb("opera")){var g=m[A]("object");r(g,e);g[C]("type","application/x-shockwave-flash");g[C]("data",d)}else g=m[A]("embed"),r(g,e),g[C]("type","application/x-shockwave-flash"),g[C]("src",d),a.videoType?a.videoType=="Google"?g[C]("bgcolor","#000000"):g[C]("wmode","transparent"):g[C]("bgcolor","#000000");d=V(c);d[s](g)}return d};Q(google[J].r,"createPlayer",google[J].r.ij);
google[J].r[F].S=function(a){this.X=a==google[J].a.Ja?!0:!1};Q(google[J].r[F],"setResultOrder",google[J].r[F].S);google[J].r[F].Fa=function(a,c){if(c){if(this.p==f){var d=V("gsc-configSetting");this.p=Db(f,"0",this.X,"gsc-configSettingCheckbox");T(d,this.p);T(d,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,Bb(R[Wa],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.p,this.X);this.p[Ea]()}else this.p&&(this.p[Pa]?this.S(google[J].a.Ja):this.S(google[J].a.dc))};google[J].g=function(){google[J].a[K](this);this.z="web";this.Qa="/GwebSearch";this.Ea="http://www.google.com/search";this.l=f;this.F=google[J].g.da;this.C=this.ma=this.Sa=this.jd=this.bb=f};P("google.search.WebSearch",google[J].g);jb(google[J].g,google[J].a);google[J].g.J="GwebSearch";Q(google[J].g,"RESULT_CLASS",google[J].g.J);google[J].g.Qb="cx";Q(google[J].g,"cxRestriction_CX",google[J].g.Qb);google[J].g.sc="cref";Q(google[J].g,"cxRestriction_CREF",google[J].g.sc);google[J].g.da="none";
Q(google[J].g,"cxRestriction_NONE",google[J].g.da);google[J].g.$h=10;google[J].g.n=[];google[J].g.P=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[J].g.n[i];google[J].g.n[i]=f;a.ca(c,d,e,g)};Q(google[J].g,"RawCompletion",google[J].g.P);google[J].g[F].Wf=function(a){var c=google[J].a.oa(google[J].g.n,this);google[J].g.P(c,a,200,f,200)};Q(google[J].g[F],"renderJson",google[J].g[F].Wf);google[J].g[F].Dj=function(a){return a[w](/\s+$/,"")[w](/^\s+/,"")};
google[J].g[F].ai=function(a){a=this.Dj(a);return a[w](/\s+/g,"_")[gb]()};
google[J].g[F].ya=function(a,c,d,e){d=d==f?google[J].a.oa(google[J].g.n,this):d;if(this.F==google[J].g.da&&this.Fj==google[J].a.kb)throw createException("The resultset size google.search.Search.FILTERED_CSE_RESULTSET can  only be used for querying filtered Custom Search Engines.");c=this.Pa(c==f?"google.search.WebSearch.RawCompletion":c,d,e);this.M&&(a=a+" "+this.M);if(this.l&&this.F!=google[J].g.da&&this.jd){var d=this.jd,g=a;this.bb!=f&&(g=a+" more:"+this.bb);d=d[w](/__HL__/,google[J][db]);this.Sa=
d=d[w](/__QUERY__/,h(g))}this.l&&this.F==google[J].g.da&&(a=a+" site:"+this.l);d="";this.l&&this.F!=google[J].g.da&&(this.F==google[J].g.Qb?d=d+"&cx="+this.l:this.F==google[J].g.sc&&(d=d+"&cref="+h(this.l)),this.bb!=f&&(a=a+" more:"+this.bb));d=d+"&q="+h(a);this.ma&&(d=d+"&safe="+this.ma);this.C&&(d+=this.C);c+=d;this.w=d;if(e&&e!=0)this.w=this.w+"&start="+e;k.google[L].GoogleLocale&&(c+="&gl="+h(k.google[L].GoogleLocale));return c};
google[J].g[F].de=function(a){a.html&&delete a.html;var c=tb(R.dym,"gs-spelling");Z(c,"gs-result");var d=m[A]("a");o(d,a.anchor);c[s](d);a.html=c};Q(google[J].g[F],"createSpellingHtml",google[J].g[F].de);
google[J].g[F].ce=function(a){a.html&&delete a.html;var c=V("gs-promotion");Z(c,"gs-result");var d;d=a.url;var e=a[Ma],g=this.u(),i=a.clicktrackUrl?{"data-cturl":a.clicktrackUrl}:f,l=U(f,"gs-title"),p=m[A]("a");p.href=d;e&&T(p,sb(e));r(p,"gs-title");g&&ma(p,g);if(i)for(var u in i)p[C](u,i[u]);l[s](p);T(c,l);d=vb(0,0);e=wb(d,0);T(c,d);if(a.image)d=a.image,d=yb(d.url,d[v],d[eb],"gs-promotion-image"),a.url&&(g=zb(a.url,"",this.u()),a.clicktrackUrl&&g[C]("data-cturl",a.clicktrackUrl),T(g,d),d=g),g=xb("gs-promotion-image-td"),
T(g,d),T(e,g);if(a.bodyLines){var g=xb(),z=V();T(e,g);T(g,z);e=a.bodyLines;for(g=0;g<e[E];g++)i=e[g],l=i[Ma],p=i.url,u=i.visibleUrl,d=V("gs-snippet"),p&&u&&(p=zb(p,u,this.u(),"gs-title"),i.clicktrackUrl&&p[C]("data-cturl",i.clicktrackUrl),T(d,p)),l&&T(d,sb(l)),T(z,d)}d=tb(a.visibleUrl,"gs-visibleUrl");T(z,d);Z(d,"gs-visibleUrl-short");a.html=c};Q(google[J].g[F],"createPromotionHtml",google[J].g[F].ce);
google[J].g[F].K=function(a){a.html&&delete a.html;ma(a,this.u()||b);a.html=google[J].q.Jc("webResult",a);if(a.clicktrackUrl)for(var c=a.html[B];c;c=c[Ja])if(c[xa]==1){c.tagName[gb]()=="a"&&c[$a]==a.unescapedUrl&&c[C]("data-cturl",a.clicktrackUrl);for(var d=c[Ka]("a"),e=0,g;g=d[e];e++)g[$a]==a.unescapedUrl&&g[C]("data-cturl",a.clicktrackUrl)}this.Ua(a.html)};Q(google[J].g[F],"createResultHtml",google[J].g[F].K);
google[J].g[F].Ba=function(a,c,d){this.Hb=this.Sa=f;var e=!1;a==f||typeof a=="string"&&a==""?(e=!1,this.l=f,this.F=google[J].g.da,this.Hb=this.bb=f):typeof a=="string"?(e=a[Da](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/))?(this.l=a,this.F=google[J].g.Qb):(this.l=a,this.F=google[J].g.da):a.siteUrl?(e=!1,this.l=a.siteUrl):a.cseId?(e=!0,this.l=a.cseId,this.F=google[J].g.Qb):a.crefUrl?(e=!0,this.l=a.crefUrl,this.F=google[J].g.sc,this.Hb=R["linked-cse-error-results"]):(e=!1,this.l=f,this.F=google[J].g.da,this.bb=
f);if(e){if(c)this.bb=this.ai(c);if(d&&d[Da](/__HL__/)&&d[Da](/__QUERY__/))this.jd=d;if(this.F==google[J].g.sc&&!this.l[Da](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/)&&n[ya](n.random()*google[J].g.$h)==0)(new Image).src="https://www.google.com/cse/tools/ping?cref="+h(this.l)+"&nocache="+Number(new Date)}};Q(google[J].g[F],"setSiteRestriction",google[J].g[F].Ba);
google[J].g[F].Y=function(a,c){if(a==google[J].a.jb)this.ma=c?c==google[J].a.hd||c==google[J].a.gd||c==google[J].a.Kf?c:f:f;if(a==google[J].a.nb)if(c)for(var d in c){var e=c[d];if(d=="lr"||d=="usg"||d=="filter"||d=="gl"||d=="richsnippet"||d=="sort")this.C==f?this.C="&":this.C+="&",this.C+=d+"="+h(e)}else this.C=f};Q(google[J].g[F],"setRestriction",google[J].g[F].Y);google[J].g[F].U=function(a){google[J].a.kb==a?this.Aa=google[J].a.kb:google[J].a[F].U[K](this,a)};
Q(google[J].g[F],"setResultSetSize",google[J].g[F].U);google[J].NoOldNames||(j("GwebSearch",google[J].g),j("GbookSearch",google[J].m),j("GblogSearch",google[J].s),j("GvideoSearch",google[J].r),j("GnewsSearch",google[J].o),j("GlocalSearch",google[J].f),j("GimageSearch",google[J].c),j("GpatentSearch",google[J].j),j("GSearch",google[J].a),j("GSearchControl",google[J].b),j("GSearchForm",google[J].L),j("GsearcherOptions",google[J].H),j("GdrawOptions",google[J].A));google[J].q={};google[J].q.cj=function(a){google[J].q.Lc.unshift(a);return google[J].q.Lc};P("google.search.Csedr.addOverride",google[J].q.cj);google[J].q.Lc=["base_",""];google[J].q.yi=function(a,c){google[J].q.Wd[a]||(google[J].q.Wd[a]=eval("[function(Vars,render,html){with(Vars)return("+a+")}][0]"));return google[J].q.Wd[a](c,google[J].q.Jc,google[J].q.gc)};google[J].q.Wd={};google[J].q.gc=function(a){var c=m.createDocumentFragment(),d=m[A]("div");for(o(d,a);d[B];)c[s](d[B]);return c};
google[J].q.Jc=function(a){if(google[J].q.Td)m[Xa][s](google[J].q.gc(google[J].q.Td)),google[J].q.Td=0;for(var c=0;!a[s];){if(c>=google[J].q.Lc[E])return google[J].q.gc(a+" not found");a=m[x](google[J].q.Lc[c++]+a)||a}for(var d={},e=1;e<arguments[E];e++)for(c in arguments[e])d[c]=arguments[e][c];try{for(var g=google[J].q.gc(""),i,l,e=0,p,u,z=function(a){a="data-"+a;u=(p=G.getAttribute(a))?google[J].q.yi(p,d):"";i.removeAttribute&&i.removeAttribute(a);return p},G=a[B];G;G=l?G:G[Ja])if(i=G[Ga](!1),
G[xa]!=1)(G[xa]!=3||G.nodeValue[Da](/\S/))&&g[s](i);else{z("foreach");if(!l&&p)d.Foreach=u&&typeof u[fb]=="function"?u:[u],c=0,l=1;if(l)if(c<d.Foreach[E])d.Cur=d.Foreach[d.Index=c++];else{l=0;continue}z("if")&&(e=0);if(p||z("elif"))if(e||!u)continue;else e=1;if(!z("attr")||u){if(g[s](i),p)for(var Y in u)if(u[Y]!=b)Y=="class"?r(i,u[Y]):Y=="style"&&lb("msie")?i[I].cssText=u[Y]:i[C](Y,u[Y])}else i=g;var Mb=z("body")?u&&u[s]?u:m.createTextNode(u):google[J].q.Jc(G,d,z("vars")?u:{});try{Mb&&i[s](Mb)}catch(Yb){}}return g}catch(Wb){return google[J].q.gc(Wb[La]()+
": "+p)}};P("google.search.Csedr.render",google[J].q.Jc);google[J].q.Td=' <div style="display:none"> <div id="base_webResult"> <div class="gs-webResult gs-result" data-vars="{longUrl:function() { var i = unescapedUrl.indexOf(visibleUrl); return i < 1 ? visibleUrl : unescapedUrl.substring(i);}}"> <div data-if="Vars.richSnippet" data-attr="0" data-body="render(\'thumbnail\',richSnippet,{url:unescapedUrl,target:target})"></div> <div class="gs-title"> <a class="gs-title" data-attr="{href:unescapedUrl,target:target}" data-body="html(title)"></a> </div> <div class="gs-snippet" data-body="html(content)"></div> <div class="gs-visibleUrl gs-visibleUrl-short" data-body="visibleUrl"></div> <div class="gs-visibleUrl gs-visibleUrl-long" data-body="longUrl()"></div> <div data-if="Vars.richSnippet && Vars.richSnippet.action" class="gs-actions" data-body="render(\'action\',richSnippet,{url:unescapedUrl,target:target})"></div> </div> </div> <div id="base_thumbnail"> <div data-attr="0" data-vars="{tn:Vars.thumbnail && thumbnail.src ? thumbnail : {src:Vars.document && document.thumbnailUrl}}"> <div data-if="tn.src"> <a class="gs-image" data-attr="{href:url,target:target}"> <img style="display: none;" class="gs-image" data-attr="{src:tn.src, width:tn.width || 100, height: tn.height}" onload="this.style.display = \'inline\'; this.parentNode.parentNode.className = \'gs-image-box gs-web-image-box\';"/> </a> </div> </div> </div> <div id="base_action"> <div data-foreach="Vars.action" data-attr="0"> <div data-attr="{\'class\': \'gs-action \' + Cur[\'class\']}" data-if="Cur.url && Cur.label"> <a class="gs-action" data-attr="{href:Cur.url,target:target}" data-body="Cur.label"></a> </div> </div> </div> </div> ';
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['search']) {(function() {var scripts = google.loader.eval.scripts['search'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.search(scripts[i]);}})();google.loader.eval.scripts['search'] = null;}})();